table Date
	dataCategory: Time

	measure 'Days In Current Quarter to Date' = COUNTROWS( DATESQTD( 'Date'[Date] ) )
		dataType: int64

	measure 'Days In Current Quarter' = COUNTROWS( DATESBETWEEN( 'Date'[Date], STARTOFQUARTER( LASTDATE( 'Date'[Date] ) ), ENDOFQUARTER( 'Date'[Date] ) ) )
		dataType: int64

	column DateKey
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: DateKey

	column Date
		dataType: dateTime
		isKey
		formatString: d. MMMM yyyy hh:mm:ss
		sourceColumn: Date

	column 'Day Number Of Week'
		dataType: int64
		summarizeBy: none
		sourceColumn: DayNumberOfWeek

	column 'Day Name Of Week'
		dataType: string
		sourceColumn: EnglishDayNameOfWeek
		sortByColumn: 'Day Number Of Week'

	column 'Day Of Month'
		dataType: int64
		summarizeBy: none
		sourceColumn: DayNumberOfMonth

	column 'Day Of Year'
		dataType: int64
		summarizeBy: none
		sourceColumn: DayNumberOfYear

	column 'Week Of Year'
		dataType: int64
		summarizeBy: none
		sourceColumn: WeekNumberOfYear

	column 'Month Name'
		dataType: string
		sourceColumn: MonthName
		sortByColumn: Month

	column Month
		dataType: int64
		summarizeBy: none
		sourceColumn: MonthNumberOfYear

	column 'Calendar Quarter'
		dataType: int64
		summarizeBy: none
		sourceColumn: CalendarQuarter

	column 'Calendar Year'
		dataType: int64
		summarizeBy: none
		sourceColumn: CalendarYear

	column 'Calendar Semester'
		dataType: int64
		summarizeBy: none
		sourceColumn: CalendarSemester

	column 'Fiscal Quarter'
		dataType: int64
		summarizeBy: none
		sourceColumn: FiscalQuarter

	column 'Fiscal Year'
		dataType: int64
		summarizeBy: none
		sourceColumn: FiscalYear

	column 'Fiscal Semester'
		dataType: int64
		summarizeBy: none
		sourceColumn: FiscalSemester

	column 'Month Year' = 'Date'[Month Name] & " " & 'Date'[Calendar Year]
		dataType: string
		lineageTag: 09b8776e-645f-4b2c-962d-0d2500c59831
		isDataTypeInferred
		sortByColumn: 'Month Year Number'

	column 'Month Year Number' = 'Date'[Calendar Year]*100 + 'Date'[Month]
		dataType: int64
		lineageTag: a10706dc-54af-4db8-b890-74e6b4ff757d
		isDataTypeInferred

	hierarchy Calendar

		level Year
			column: 'Calendar Year'

		level Semester
			column: 'Calendar Semester'

		level Quarter
			column: 'Calendar Quarter'

		level Month
			column: 'Month Name'

		level Day
			column: 'Day Of Month'

	hierarchy Fiscal

		level 'Fiscal Year'
			column: 'Fiscal Year'

		level 'Fiscal Semester'
			column: 'Fiscal Semester'

		level 'Fiscal Quarter'
			column: 'Fiscal Quarter'

		level Month
			column: 'Month Name'

		level Day
			column: 'Day Of Month'

	hierarchy 'Production Calendar'

		level Year
			column: 'Calendar Year'

		level Week
			column: 'Week Of Year'

		level 'Week Day'
			column: 'Day Name Of Week'

	hierarchy Year-Month
		lineageTag: d60b244a-83a7-4327-b6bf-47efd434eaa5

		level 'Calendar Year'
			lineageTag: e20f40a0-fc60-45b0-a835-2261f0e43191
			column: 'Calendar Year'

		level 'Month Year'
			lineageTag: 125dd9c0-b8b2-4cd9-936e-c42644a712e7
			column: 'Month Year'

	partition Date = query
		source
			query = SELECT [dbo].[DimDate].* 		FROM [dbo].[DimDate]
			dataSource: 'SqlServer localhost'

		annotation QueryEditorSerialization

		annotation TableWidgetSerialization

	annotation _TM_ExtProp_DbSchemaName = dbo

	annotation _TM_ExtProp_DbTableName = DimDate

	annotation _TM_ExtProp_QueryDefinition = ```
			      SELECT [dbo].[DimDate].*   FROM [dbo].[DimDate] 
			```

