{
  "name": "SpaceParts",
  "compatibilityLevel": 1600,
  "model": {
    "name": "SpaceParts",
    "culture": "en-US",
    "discourageImplicitMeasures": true,
    "dataSources": [
      {
        "type": "structured",
        "name": "SpacePartsDW",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "connectionstring": "",
            "server": "te3-training-eu.database.windows.net",
            "database": "SpacePartsCoDW"
          }
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "EncryptConnection": true,
          "Username": "dwreader",
          "PrivacySetting": "Public"
        }
      }
    ],
    "tables": [
      {
        "name": "1) Selected Metric",
        "description": "It lets you select a Metric.",
        "lineageTag": "31535870-007d-4636-8348-2f06b750951d",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Order",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Order]",
            "lineageTag": "734455ee-3587-4f7b-bdd9-34f849747e7d"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Select a Measure",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Select a Measure]",
            "sortByColumn": "Order",
            "lineageTag": "16dc4342-12d1-4da6-89d8-63ba7be01ddf"
          }
        ],
        "partitions": [
          {
            "name": "1) Selected Metric",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "SELECTCOLUMNS(",
                "    'Z01CG2 - Value (Budget Rate)',",
                "        \"Select a Measure\", 'Z01CG2 - Value (Budget Rate)'[Measure],",
                "        \"Order\", 'Z01CG2 - Value (Budget Rate)'[Ordinal]",
                ")"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Static Tables"
          }
        ]
      },
      {
        "name": "2) Selected Unit",
        "description": [
          "This is a disconnected table for Measure Selection.",
          "It lets you select a Unit."
        ],
        "lineageTag": "8db601bc-67fe-4a66-8b3e-5751e675a807",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Order",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Order]",
            "lineageTag": "6b618add-eff1-447d-b625-90bab65824d7"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Select a Unit",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Select a Unit]",
            "sortByColumn": "Order",
            "lineageTag": "01083816-a18e-4ea5-9fba-28c9b19b5f74"
          }
        ],
        "partitions": [
          {
            "name": "2) Selected Unit",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "SELECTCOLUMNS(",
                "    'Z02CG1 - Unit',",
                "        \"Select a Unit\", 'Z02CG1 - Unit'[Unit],",
                "        \"Order\", 'Z02CG1 - Unit'[Ordinal]",
                ") "
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Static Tables"
          }
        ]
      },
      {
        "name": "3) Selected Target",
        "description": [
          "This is a disconnected table for Measure Selection.",
          "It lets you select a Target."
        ],
        "lineageTag": "faedb0d7-81a5-4a5b-aa77-569ccb6f80d4",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "MTD Slicer",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[MTD Slicer]",
            "sortByColumn": "Order",
            "lineageTag": "02184b60-9463-42cc-9353-3076dcfd57d1"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Order",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Order]",
            "lineageTag": "6549343f-cc13-417c-a7ec-4052e86c701d"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Select a Target",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Select a Target]",
            "sortByColumn": "Order",
            "lineageTag": "d66a7492-deb6-4fc5-8bf4-9ea15c424cfc"
          }
        ],
        "partitions": [
          {
            "name": "3) Selected Target",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "SELECTCOLUMNS (",
                "    'Z03CG1 - Sales Target',",
                "    \"Select a Target\", 'Z03CG1 - Sales Target'[Target],",
                "    \"Order\", 'Z03CG1 - Sales Target'[Ordinal],",
                "    \"MTD Slicer\",",
                "        VAR _TARGET = 'Z03CG1 - Sales Target'[Target]",
                "        RETURN",
                "            SWITCH (",
                "                TRUE (),",
                "                _TARGET = \"Budget\",         \"Gross Sales MTD vs. Budget\",",
                "                _TARGET = \"Forecast\",       \"Gross Sales MTD vs. FCST\",",
                "                _TARGET = \"1 Year Prior\",   \"Gross Sales MTD vs. 1YP\",",
                "                _TARGET = \"2 Years Prior\",  \"Gross Sales MTD vs. 2YP\"",
                "            )",
                ")"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Static Tables"
          }
        ]
      },
      {
        "name": "4) Selected Period",
        "description": [
          "This is a disconnected table for Measure Selection.",
          "It lets you select a Period"
        ],
        "lineageTag": "d0747f9f-bab0-419e-87fb-7ae01f97a523",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "MTD",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[MTD]",
            "sortByColumn": "Order",
            "displayFolder": "Columns\\0. Select a Period",
            "lineageTag": "c9ee146b-ada4-4f64-b3ec-5367e8e35c2e"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Order",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Order]",
            "displayFolder": "Columns\\1. Order",
            "lineageTag": "28ecb9f2-1504-4a33-9da4-5bcfcc9c3317"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Period",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Period]",
            "sortByColumn": "Order",
            "lineageTag": "1f98320e-9b80-4c14-abbd-50b713f55446"
          },
          {
            "type": "calculatedTableColumn",
            "name": "QTD",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[QTD]",
            "sortByColumn": "Order",
            "displayFolder": "Columns\\0. Select a Period",
            "lineageTag": "32c56d15-bb0d-4567-b661-75ae39b13044"
          },
          {
            "type": "calculatedTableColumn",
            "name": "YTD",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[YTD]",
            "sortByColumn": "Order",
            "displayFolder": "Columns\\0. Select a Period",
            "lineageTag": "25f552c2-f3ce-428e-a61c-dd66630c4bef"
          }
        ],
        "partitions": [
          {
            "name": "4) Selected Period",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "UNION (",
                "    ROW (",
                "        \"Period\", {\"Full Period\"},",
                "        \"Order\", {0},",
                "        \"MTD\", {\"Full Month\"},",
                "        \"QTD\", {\"Full Quarter\"},",
                "        \"YTD\", {\"Full Year\"}",
                "    ),",
                "    ROW (",
                "        \"Period\", {\"Period-to-Date\"},",
                "        \"Order\", {1},",
                "        \"MTD\", {\"MTD\"},",
                "        \"QTD\", {\"QTD\"},",
                "        \"YTD\", {\"YTD\"}",
                "    )",
                ")"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Static Tables"
          }
        ]
      },
      {
        "name": "Brands",
        "lineageTag": "5e2b506f-5416-43b6-b5f6-160cbd60ab96",
        "columns": [
          {
            "name": "Brand Class",
            "dataType": "string",
            "sourceColumn": "Class",
            "displayFolder": "1. Brand Hierarchy",
            "lineageTag": "e3b11f72-6c3d-4151-a219-5df0d87c75ab"
          },
          {
            "name": "Brand Tier",
            "dataType": "string",
            "sourceColumn": "Flagship",
            "displayFolder": "1. Brand Hierarchy",
            "lineageTag": "16be3840-ea52-4cb5-bbc1-f866be4193aa"
          },
          {
            "name": "Brand",
            "dataType": "string",
            "sourceColumn": "Brand",
            "displayFolder": "1. Brand Hierarchy",
            "lineageTag": "026cc844-0d0a-444c-b3e6-4755b618ee1c"
          },
          {
            "name": "Product Brand VP",
            "dataType": "string",
            "sourceColumn": "Product Brand VP",
            "displayFolder": "3. Managers",
            "lineageTag": "cd36ed0c-b7f0-404f-b8a0-ced180569814"
          },
          {
            "name": "Sub Brand Type",
            "dataType": "string",
            "sourceColumn": "Type",
            "displayFolder": "2. Brand Attributes",
            "lineageTag": "f1c1b582-1730-4828-a57c-9e4148579d68"
          },
          {
            "name": "Sub Brand",
            "dataType": "string",
            "sourceColumn": "Sub Brand",
            "displayFolder": "1. Brand Hierarchy",
            "lineageTag": "64d691d4-8f81-40ad-9626-f50a0fb25bfa"
          }
        ],
        "partitions": [
          {
            "name": "Brands",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SpacePartsDW\",",
                "    Data = Source{[Schema=\"Dimview\",Item=\"Brands\"]}[Data]",
                "in",
                "    Data"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Brand Hierarchy",
            "displayFolder": "1. Brand Hierarchy",
            "lineageTag": "084d70b4-6315-42f4-9fa3-84fac3f33e6b",
            "levels": [
              {
                "name": "Class",
                "ordinal": 0,
                "column": "Brand Class",
                "lineageTag": "5457edb0-3439-4d56-baf9-e14078ae42d6"
              },
              {
                "name": "Flagship",
                "ordinal": 1,
                "column": "Brand Tier",
                "lineageTag": "63f540d1-6f1a-4224-b13d-e5e8cf74727c"
              },
              {
                "name": "Brand",
                "ordinal": 2,
                "column": "Brand",
                "lineageTag": "47d9b70c-0dbe-4719-9c28-498808e9fe1b"
              },
              {
                "name": "Sub Brand",
                "ordinal": 3,
                "column": "Sub Brand",
                "lineageTag": "4cf48791-4d41-4f0d-988b-385822b676aa"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Dimension Tables"
          }
        ]
      },
      {
        "name": "Budget",
        "lineageTag": "a6b0eb60-264f-474d-a8fe-ac16f65fbc35",
        "columns": [
          {
            "name": "Budget (EUR)",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Total Budget",
            "displayFolder": "2. Facts",
            "lineageTag": "3f44e27b-e38e-489b-ab39-80615cb15782"
          },
          {
            "name": "Customer Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Customer Key",
            "displayFolder": "1. Keys",
            "lineageTag": "f748b942-7ab6-4a6a-800e-7e1acfe97bca"
          },
          {
            "name": "Month",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Month",
            "displayFolder": "1. Keys",
            "lineageTag": "23bef58e-18a2-4193-856d-2498101b880c"
          },
          {
            "name": "Product Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Product Key",
            "displayFolder": "1. Keys",
            "lineageTag": "f70c2f53-c04d-46a5-a162-d54d50bfffa0"
          }
        ],
        "partitions": [
          {
            "name": "Budget",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SpacePartsDW\",",
                "    Data = Source{[Schema=\"Factview\",Item=\"Budget\"]}[Data],",
                "    #\"Select Columns\" = Table.SelectColumns ( Data, {\"Customer Key\", \"Month\", \"Product Key\", \"Total Budget\"} )",
                "in",
                "    #\"Select Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "2022 Budget Achievement %",
            "expression": [
              "",
              "VAR _Sales =",
              "    CALCULATE (",
              "        [Gross Sales],",
              "        'Date'[Calendar Year Number (ie 2021)]",
              "            = 2022,",
              "        'Date'[IsDateInScope] = TRUE ( ),",
              "        DATESYTD ( 'Date'[Date] )",
              "    )",
              "VAR _Budget =",
              "    CALCULATE (",
              "        [Total Budget],",
              "        'Date'[Calendar Year Number (ie 2021)]",
              "            = 2022,",
              "        'Date'[IsDateInScope] = TRUE ( ),",
              "        DATESYTD ( 'Date'[Date] )",
              "    )",
              "VAR _Delta = _Sales - _Budget",
              "VAR _Perc = DIVIDE ( _Delta, _Budget )",
              "RETURN",
              "    _Perc"
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "f1e22bd1-bd4f-487d-84e0-7a4b863f1088"
          },
          {
            "name": "Budget MTD vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Budget MTD]",
              "VAR _DELTA  = [MTD Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "Measures\\ii. MTD",
            "lineageTag": "8eb42713-706d-436a-a1c4-dda1c25494e1"
          },
          {
            "name": "Budget MTD vs. Gross Sales (Δ)",
            "expression": [
              "",
              "[MTD Gross Sales] - [Budget MTD]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "Measures\\ii. MTD",
            "lineageTag": "dae40a70-a31d-41e3-bf4d-f77b08aefe31"
          },
          {
            "name": "Budget MTD",
            "expression": [
              "",
              "-- Calculates the target for the current month/year selection",
              "VAR _CURRENT_MONTH_VALUE =",
              "    CALCULATE (",
              "        [Budget],",
              "        ALL ( 'Date' ),",
              "        VALUES ( 'Date'[Calendar Month Year (ie Jan 21)] )",
              "    ) ",
              "",
              "-- Computes rate at which Budget increases through the month",
              "VAR _CURRENT_MONTH_PERC_WORKDAYS_MTD =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] ),",
              "            'Date'[IsDateInScope] = TRUE",
              "        ),",
              "        1.035",
              "    )",
              "",
              "VAR _CURRENT_MONTH_PERC_WORKDAYS =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] )",
              "        ),",
              "        1.035",
              "    )",
              "",
              "VAR _PERIOD =",
              "    SELECTEDVALUE (",
              "        '4) Selected Period'[Period]",
              "    )",
              "VAR _HASONEMONTH =",
              "    HASONEVALUE (",
              "        'Date'[Calendar Month Year (ie Jan 21)]",
              "    )",
              "RETURN",
              "    -- return MTD value if a month is selected",
              "    IF.EAGER (",
              "        _HASONEMONTH",
              "            && _PERIOD = \"Full Period\",",
              "        _CURRENT_MONTH_PERC_WORKDAYS",
              "            * _CURRENT_MONTH_VALUE,",
              "",
              "        IF (",
              "            _HASONEMONTH,",
              "            _CURRENT_MONTH_PERC_WORKDAYS_MTD",
              "                * _CURRENT_MONTH_VALUE",
              "        )",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\ii. MTD",
            "lineageTag": "e7c3e0f7-bc73-4250-93f4-17d3b3e06d2e"
          },
          {
            "name": "Budget QTD vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Budget QTD]",
              "VAR _DELTA  = [Gross Sales] - [Budget QTD]",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "Measures\\iii. QTD",
            "lineageTag": "4b634367-f3b3-4b7e-a4c5-11ae1f0005a3"
          },
          {
            "name": "Budget QTD vs. Gross Sales (Δ)",
            "expression": [
              "",
              "[Gross Sales] - [Budget QTD]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "Measures\\iii. QTD",
            "lineageTag": "2a13f546-675f-46dc-80b9-e457b2aa9d01"
          },
          {
            "name": "Budget QTD",
            "expression": [
              "",
              "VAR _DATES_QTD =",
              "    CALCULATETABLE (",
              "        DATESQTD ('Date'[Date]),",
              "        'Date'[IsThisMonth] = FALSE",
              "    )",
              "VAR _CURRENT_MONTH_Budget = [Budget MTD]",
              "VAR QTD_BUDGET_BEFORE_THIS_MONTH = CALCULATE ([Budget], _DATES_QTD)",
              "VAR _RESULT = _CURRENT_MONTH_Budget + QTD_BUDGET_BEFORE_THIS_MONTH",
              "RETURN",
              "    _RESULT"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\iii. QTD",
            "lineageTag": "377282fa-8f79-4de5-b02c-9ed97ed804ff"
          },
          {
            "name": "Budget vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Budget]",
              "VAR _DELTA  = [Gross Sales] - [Budget]",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "e5eb5098-0e4f-4d23-b7c5-bb287ff8bb59"
          },
          {
            "name": "Budget vs. Gross Sales (Δ)",
            "expression": [
              "",
              "[Gross Sales] - [Budget]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "824b1d58-869a-408c-a12e-ccdf950300ef"
          },
          {
            "name": "Budget YTD vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Budget YTD]",
              "VAR _DELTA  = [Gross Sales] - [Budget YTD]",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "Measures\\iv. YTD",
            "lineageTag": "99f3b31f-c3eb-4f23-8403-959bdcf5cae0"
          },
          {
            "name": "Budget YTD vs. Gross Sales (Δ)",
            "expression": [
              "",
              "[Gross Sales] - [Budget YTD]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "Measures\\iv. YTD",
            "lineageTag": "ee4a5a38-3679-4596-afa7-5f613a87ed87"
          },
          {
            "name": "Budget YTD",
            "expression": [
              "",
              "VAR _DATES_YTD =",
              "    CALCULATETABLE (",
              "        DATESYTD ( 'Date'[Date] ),",
              "        'Date'[IsThisMonth] = FALSE",
              "    )",
              "VAR _CURRENT_MONTH_Budget = [Budget MTD]",
              "VAR QTD_Budget_BEFORE_THIS_MONTH =",
              "    CALCULATE ( [Budget], _DATES_YTD )",
              "VAR _RESULT =",
              "    _CURRENT_MONTH_Budget",
              "        + QTD_Budget_BEFORE_THIS_MONTH",
              "RETURN",
              "    _RESULT"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\iv. YTD",
            "lineageTag": "4cfd4bbc-3ee3-4224-8224-89ba77bfd212"
          },
          {
            "name": "Budget",
            "expression": [
              "",
              "IF.EAGER(",
              "    HASONEVALUE( '2) Selected Unit'[Select a Unit] )",
              "        && ",
              "    HASONEVALUE( 'Exchange Rate'[Currency] ),",
              "",
              "    VAR _SELECTED_CURRENCY = ",
              "        SELECTEDVALUE( 'Exchange Rate'[Currency] )",
              "",
              "    VAR _SELECTED_RATE_TYPE = ",
              "        SELECTEDVALUE( '2) Selected Unit'[Select a Unit] )",
              "    ",
              "    VAR _SELECTED_BUDGET_RATE =",
              "        MAX( 'Exchange Rate'[Rate] )",
              "        ",
              "    VAR _SELECTED_MONTHLY_RATE =",
              "        ADDCOLUMNS(",
              "            SUMMARIZE(",
              "                'Exchange Rate',",
              "                'Date'[Calendar Month Year (ie Jan 21)]",
              "            ),",
              "            \"Curr\", ",
              "            CALCULATE ( ",
              "                MAX( 'Exchange Rate'[Rate] ) ",
              "            )",
              "        )",
              "        ",
              "    RETURN",
              "",
              "    IF(",
              "        _SELECTED_RATE_TYPE = \"Value (Budget Rate)\",",
              "        SUM ( 'Budget'[Budget (EUR)]) ",
              "        * ",
              "        _SELECTED_BUDGET_RATE,",
              "        ",
              "        IF(",
              "            _SELECTED_RATE_TYPE = \"Value (Monthly Rate)\",",
              "            SUMX(",
              "                _SELECTED_MONTHLY_RATE,",
              "                CALCULATE( ",
              "                    SUM ( 'Budget'[Budget (EUR)])",
              "                )",
              "                * [Curr]",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "60d839fc-8ab6-4b78-af3f-80bc6305c529"
          },
          {
            "name": "Total Budget",
            "expression": [
              "",
              "    VAR _SelectedRate = MAX ( 'Exchange Rate'[Rate] )",
              "RETURN",
              "    SUM ( 'Budget'[Budget (EUR)] ) * _SelectedRate"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "1cfbbd0e-ec57-4948-8e7c-e8a520d634c7"
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Fact Tables"
          }
        ]
      },
      {
        "name": "Budget Rate",
        "isHidden": true,
        "lineageTag": "68dde8df-0ca5-4974-9afa-a3d1fc7dcf1f",
        "columns": [
          {
            "name": "Currency System",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Currency System",
            "displayFolder": "3. Other Currency Fields",
            "lineageTag": "f92a040a-f088-449b-8486-33aeeef0c9b2"
          },
          {
            "name": "From Currency",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "From Currency",
            "displayFolder": "2. Keys",
            "lineageTag": "df013c22-0791-4223-9fe0-f45c70d95063"
          },
          {
            "name": "Rate",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "Rate",
            "displayFolder": "1. Facts",
            "lineageTag": "46c64843-a8c8-49af-9770-8144db4c3640"
          },
          {
            "name": "To Currency",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "To Currency",
            "displayFolder": "3. Other Currency Fields",
            "lineageTag": "d7d777a5-9b43-429b-a5eb-fb1ab1549af7"
          }
        ],
        "partitions": [
          {
            "name": "Budget Rate",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SpacePartsDW\",",
                "    Data = Source{[Schema=\"Dimview\",Item=\"Budget Rate\"]}[Data]",
                "in",
                "    Data"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Dimension Tables"
          }
        ]
      },
      {
        "name": "Customers",
        "lineageTag": "c247ff24-c33b-4a9e-96f6-95d1e36e4be4",
        "columns": [
          {
            "name": "Account Manager",
            "dataType": "string",
            "sourceColumn": "Account Manager",
            "displayFolder": "3. Managers",
            "lineageTag": "67fe957e-20ff-43ea-ae81-6e377ee37f71"
          },
          {
            "name": "Account Name",
            "dataType": "string",
            "sourceColumn": "Account Name",
            "displayFolder": "1. Customer Hierarchy",
            "lineageTag": "a0b900e7-c1c7-4a87-aa1a-a52a61ece17d"
          },
          {
            "name": "Account Type",
            "dataType": "string",
            "sourceColumn": "Account Type",
            "displayFolder": "1. Customer Hierarchy",
            "lineageTag": "a0a0a72d-6c54-4e38-89c2-acf0084d375a"
          },
          {
            "name": "Customer Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Customer Key",
            "displayFolder": "4. Keys",
            "lineageTag": "8138d992-9c95-4468-ad79-4607af12e82e"
          },
          {
            "name": "Customer Sold-To Name",
            "dataType": "string",
            "sourceColumn": "Customer Sold-To Name",
            "displayFolder": "1. Customer Hierarchy",
            "lineageTag": "57a55013-2487-4f85-9924-ba95d30adf0c"
          },
          {
            "name": "Key Account Manager",
            "dataType": "string",
            "sourceColumn": "Key Account Manager",
            "displayFolder": "3. Managers",
            "lineageTag": "72fc9786-6102-4514-a9f0-35cfc60809b4"
          },
          {
            "name": "Key Account Name",
            "dataType": "string",
            "sourceColumn": "Key Account Name",
            "displayFolder": "1. Customer Hierarchy",
            "lineageTag": "449b79b3-9236-4e65-9f9e-2ac349ace7be"
          },
          {
            "name": "Station",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Station",
            "displayFolder": "4. Keys",
            "lineageTag": "22b532a7-95c9-4055-98bd-f6c8624e21ea"
          },
          {
            "name": "Transaction Type",
            "dataType": "string",
            "sourceColumn": "Transaction Type",
            "displayFolder": "2. Other Customer Attributes",
            "lineageTag": "d288644d-e68b-417a-b6ad-c229a86c5de4"
          }
        ],
        "partitions": [
          {
            "name": "Customers",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "",
                "  // Data Source",
                "  Source = #\"SpacePartsDW\", ",
                "",
                "  // Step",
                "  Data = Source",
                "    {",
                "      [",
                "        Schema = \"Dimview\", ",
                "        Item   = \"Customers\"",
                "      ]",
                "    }",
                "    [Data]",
                "",
                "// Result",
                "in",
                "  Data"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "# Customers",
            "expression": [
              "",
              "COUNTROWS (",
              "    VALUES ( 'Customers'[Account Name] )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures",
            "lineageTag": "b99fd2f5-eff7-4fe3-8fee-b4f9e758f2bf"
          },
          {
            "name": "# Key Accounts",
            "expression": [
              "",
              "COUNTROWS (",
              "    VALUES ( 'Customers'[Key Account Name] )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures",
            "lineageTag": "19c6259b-8906-4d55-9f07-f38335a43d03"
          }
        ],
        "hierarchies": [
          {
            "name": "Customer Hierarchy",
            "displayFolder": "1. Customer Hierarchy",
            "lineageTag": "21ce8263-4484-4671-9324-29eb1d5fb394",
            "levels": [
              {
                "name": "Account Type",
                "ordinal": 0,
                "column": "Account Type",
                "lineageTag": "63750788-6ce3-468b-acfb-48561f995e59"
              },
              {
                "name": "Key Account Name",
                "ordinal": 1,
                "column": "Key Account Name",
                "lineageTag": "695025d0-549e-4b7c-b020-926a32b43d89"
              },
              {
                "name": "Account Name",
                "ordinal": 2,
                "column": "Account Name",
                "lineageTag": "4701a595-a719-4c4c-a262-0961ea84c24b"
              },
              {
                "name": "Customer Sold-To Name",
                "ordinal": 3,
                "column": "Customer Sold-To Name",
                "lineageTag": "24730ed3-e089-46de-bd4c-26f648c4a791"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Dimension Tables"
          }
        ]
      },
      {
        "name": "Date",
        "lineageTag": "0bb45e29-3908-422d-ade4-4100434bdfa4",
        "dataCategory": "Time",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Month # (ie 1)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Month # (ie 1)]",
            "displayFolder": "3. Month",
            "lineageTag": "e19f6bb4-ef58-4a9b-9938-a9f53054cfca"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Month (ie Jan)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Month (ie Jan)]",
            "sortByColumn": "Calendar Month # (ie 1)",
            "displayFolder": "3. Month",
            "lineageTag": "40d9d72e-8593-4b4b-a7bc-78a324b1decb"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Month Day (i.e. 0105)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Month Day (i.e. 0105)]",
            "displayFolder": "3. Month",
            "lineageTag": "6e7c0f3a-b2bb-411a-a0a7-e267d7807ab4"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Month Day (i.e. Jan 05)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Month Day (i.e. Jan 05)]",
            "sortByColumn": "Calendar Month Day (i.e. 0105)",
            "displayFolder": "3. Month",
            "lineageTag": "1b09698b-a90f-40ce-9596-6c6047ebe042"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Month Year (ie Jan 21)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Month Year (ie Jan 21)]",
            "sortByColumn": "Calendar Year Month (ie 202101)",
            "displayFolder": "3. Month",
            "lineageTag": "edb084ec-790c-4fee-a229-e24044d12bd4"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Quarter (ie Q1)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Quarter (ie Q1)]",
            "displayFolder": "2. Quarter",
            "lineageTag": "0808e9ee-085c-4934-9b9d-c647eba54590"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Quarter Year (ie Q1 2021)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Quarter Year (ie Q1 2021)]",
            "sortByColumn": "Calendar Year Quarter (ie 202101)",
            "displayFolder": "2. Quarter",
            "lineageTag": "d8f8780d-8364-4be5-ad87-fb1d7e8bb57c"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Week EU (ie WK25)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Week EU (ie WK25)]",
            "sortByColumn": "Calendar Week Number EU (ie 25)",
            "displayFolder": "4. Week",
            "lineageTag": "da853b79-633f-4869-b291-880aa11452ad"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Week ISO (ie WK25)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Week ISO (ie WK25)]",
            "sortByColumn": "Calendar Week Number ISO (ie 25)",
            "displayFolder": "4. Week",
            "lineageTag": "ef48982f-eb1c-4196-8059-9a69d4a1c7fe"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Week Number EU (ie 25)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Week Number EU (ie 25)]",
            "displayFolder": "4. Week",
            "lineageTag": "3eb012c2-1bb5-4cc3-bf3e-4d98a1fbfd27"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Week Number ISO (ie 25)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Week Number ISO (ie 25)]",
            "displayFolder": "4. Week",
            "lineageTag": "ae46b8f1-44d5-450d-b322-33f5ecb3a0dc"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Week Number US (ie 25)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Week Number US (ie 25)]",
            "displayFolder": "4. Week",
            "lineageTag": "ee4f45a3-e866-4cd7-9a08-6b8b3e96cef4"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Week US (ie WK25)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Week US (ie WK25)]",
            "sortByColumn": "Calendar Week Number US (ie 25)",
            "displayFolder": "4. Week",
            "lineageTag": "54b2a8dd-1d3d-4350-8e50-ea3c2aa70603"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year (ie 2021)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Year (ie 2021)]",
            "sortByColumn": "Calendar Year Number (ie 2021)",
            "displayFolder": "1. Year",
            "lineageTag": "3fb515aa-1cf5-4e35-9368-26ba9fe9609b"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year Month (ie 202101)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Year Month (ie 202101)]",
            "displayFolder": "3. Month",
            "lineageTag": "2063cb48-7333-440e-acc1-5d12b4ef4641"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year Number (ie 2021)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Year Number (ie 2021)]",
            "displayFolder": "1. Year",
            "lineageTag": "cf2e5156-c81b-4636-b66b-f9b439f92d2d"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year Quarter (ie 202101)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Year Quarter (ie 202101)]",
            "displayFolder": "2. Quarter",
            "lineageTag": "6303b430-6995-46b7-82b1-4cd3102b9d6d"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year Week Number EU (ie 202125)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Year Week Number EU (ie 202125)]",
            "displayFolder": "4. Week",
            "lineageTag": "9239173d-70a1-4fb7-8ef8-b6b580e4c576"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year Week Number ISO (ie 202125)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Year Week Number ISO (ie 202125)]",
            "displayFolder": "4. Week",
            "lineageTag": "b7562b0b-32a5-49ab-8c2b-c0f933e8e272"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year Week Number US (ie 202125)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Year Week Number US (ie 202125)]",
            "displayFolder": "4. Week",
            "lineageTag": "6369e90a-ee7b-4da8-9884-0457e4366927"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isKey": true,
            "sourceColumn": "[Date]",
            "displayFolder": "6. Calendar Date",
            "lineageTag": "09572bf6-eb54-4fb5-8ad1-1dee0c198ec0"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsActualToday",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsActualToday]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "c158c062-5f41-4066-9b71-07040d22ea1c"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsBeforeThisMonth",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsBeforeThisMonth]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "3a3ebb62-fa77-42c9-94e7-7dd38cbcc9ca"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsDateInScope",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsDateInScope]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "4bca850c-4687-484d-a941-8b82c8ac9435"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsHoliday",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsHoliday]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "ee3e6d01-2621-4a08-b25a-591318b53703"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsLastMonth",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsLastMonth]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "3cf4eb07-f6c1-4297-a58d-37d7bc7c0c5d"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsRefDate",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsRefDate]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "a0711613-1ed5-4931-be77-c97fe1f71a3d"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsThisMonth",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsThisMonth]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "51bcf435-6619-4d65-8dcf-b861329e2a51"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsThisQuarter",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsThisQuarter]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "3701707f-517d-4b04-a559-747ad90fa4ec"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsThisWeek",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsThisWeek]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "19c5b6d5-141d-4298-b0db-d60212c2707e"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsThisYear",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsThisYear]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "016d6200-8ae0-43de-85c0-fcf96e65fab3"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsWeekday",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsWeekday]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "bf956c16-2355-499b-b503-b88553b552df"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsYTD",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsYTD]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "1be5363a-e1d5-42c9-b335-83e6b593273c"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Weekday Name (i.e. Monday)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Weekday Name (i.e. Monday)]",
            "sortByColumn": "Weekday Number EU (i.e. 1)",
            "displayFolder": "5. Weekday / Workday\\Weekday",
            "lineageTag": "ef85b198-9069-484e-b7d7-25425c242d1a"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Weekday Number EU (i.e. 1)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Weekday Number EU (i.e. 1)]",
            "displayFolder": "5. Weekday / Workday\\Weekday",
            "lineageTag": "6d6d80e2-e8a9-4d10-acff-4d7531522034"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Weekday Short (i.e. Mon)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Weekday Short (i.e. Mon)]",
            "sortByColumn": "Weekday Number EU (i.e. 1)",
            "displayFolder": "5. Weekday / Workday\\Weekday",
            "lineageTag": "41ab7d65-b8a5-4011-9814-92b110086158"
          },
          {
            "type": "calculated",
            "name": "Workdays MTD %",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": [
              "DIVIDE (",
              "    'Date'[Workdays MTD],",
              "    /* Number of weekdays MTD for selected month */",
              "    CALCULATE (",
              "        [# Workdays in Selected Month],",
              "        ALLEXCEPT ( 'Date', 'Date'[Calendar Month Year (ie Jan 21)] )",
              "    ),",
              "    /* Total number of weekdays for selected month */",
              "    0",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "5. Weekday / Workday\\Workdays",
            "lineageTag": "cd816ac9-657f-4f27-ae68-ba35c84475f5"
          },
          {
            "type": "calculated",
            "name": "Workdays MTD",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": [
              "VAR _Holidays =",
              "    CALCULATETABLE (",
              "        DISTINCT ('Date'[Date]),",
              "        'Date'[IsHoliday] <> TRUE",
              "    )",
              "VAR _WeekdayName = CALCULATE ( SELECTEDVALUE ( 'Date'[Weekday Short (i.e. Mon)] ) )",
              "VAR _WeekendDays = SWITCH (",
              "        _WeekdayName,",
              "        \"Sat\", 2,",
              "        \"Sun\", 3,",
              "        0",
              "    )",
              "VAR _WorkdaysMTD =",
              "    CALCULATE (",
              "        NETWORKDAYS (",
              "            CALCULATE (",
              "                MIN ('Date'[Date]),",
              "                ALLEXCEPT ('Date', 'Date'[Calendar Month Year (ie Jan 21)])",
              "            ),",
              "            CALCULATE (MAX ('Date'[Date]) - _WeekendDays),",
              "            1,",
              "            _Holidays",
              "        )",
              "    )",
              "        + 1",
              "RETURN",
              "    IF (_WorkdaysMTD < 1, 1, _WorkdaysMTD)"
            ],
            "displayFolder": "5. Weekday / Workday\\Workdays",
            "lineageTag": "f66ce538-103c-476a-b5b7-fdf95a7d756e"
          },
          {
            "type": "calculated",
            "name": "Workdays QTD",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": [
              "VAR _Holidays =",
              "    CALCULATETABLE (",
              "        DISTINCT ('Date'[Date]),",
              "        'Date'[IsHoliday] <> TRUE",
              "    )",
              "VAR _WeekdayName = CALCULATE ( SELECTEDVALUE ( 'Date'[Weekday Short (i.e. Mon)] ) )",
              "VAR _WeekendDays = SWITCH (",
              "        _WeekdayName,",
              "        \"Sat\", 2,",
              "        \"Sun\", 3,",
              "        0",
              "    )",
              "VAR _WorkdaysMTD =",
              "    CALCULATE (",
              "        NETWORKDAYS (",
              "            CALCULATE (",
              "                MIN ('Date'[Date]),",
              "                ALLEXCEPT ('Date', 'Date'[Calendar Quarter Year (ie Q1 2021)])",
              "            ),",
              "            CALCULATE (MAX ('Date'[Date]) - _WeekendDays),",
              "            1,",
              "            _Holidays",
              "        )",
              "    )",
              "        + 1",
              "RETURN",
              "    IF (_WorkdaysMTD < 1, 1, _WorkdaysMTD)"
            ],
            "displayFolder": "5. Weekday / Workday\\Workdays",
            "lineageTag": "9d01d75f-4942-4b6a-9217-a702574aaf64"
          },
          {
            "type": "calculated",
            "name": "Workdays YTD",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": [
              "VAR _Holidays =",
              "    CALCULATETABLE (",
              "        DISTINCT ('Date'[Date]),",
              "        'Date'[IsHoliday] <> TRUE",
              "    )",
              "VAR _WeekdayName = CALCULATE ( SELECTEDVALUE ( 'Date'[Weekday Short (i.e. Mon)] ) )",
              "VAR _WeekendDays = SWITCH (",
              "        _WeekdayName,",
              "        \"Sat\", 2,",
              "        \"Sun\", 3,",
              "        0",
              "    )",
              "VAR _WorkdaysMTD =",
              "    CALCULATE (",
              "        NETWORKDAYS (",
              "            CALCULATE (",
              "                MIN ('Date'[Date]),",
              "                ALLEXCEPT ('Date', 'Date'[Calendar Year (ie 2021)])",
              "            ),",
              "            CALCULATE (MAX ('Date'[Date]) - _WeekendDays),",
              "            1,",
              "            _Holidays",
              "        )",
              "    )",
              "        + 1",
              "RETURN",
              "    IF (_WorkdaysMTD < 1, 1, _WorkdaysMTD)"
            ],
            "displayFolder": "5. Weekday / Workday\\Workdays",
            "lineageTag": "439c9bb8-b5df-4014-92dd-384c1bcdaf5c"
          },
          {
            "type": "calculatedTableColumn",
            "name": "YYYYMMDD",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[YYYYMMDD]",
            "displayFolder": "6. Calendar Date",
            "lineageTag": "b8f541e5-acb5-4fdf-83b9-c031aee1e282"
          }
        ],
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "-- Reference date for the latest date in the report",
                "-- Until when the business wants to see data in reports",
                "VAR _Refdate_Measure = [RefDate]",
                "VAR _Today = TODAY ( )",
                "",
                "-- Replace with \"Today\" if [RefDate] evaluates blank",
                "VAR _Refdate = IF ( ISBLANK ( _Refdate_Measure ), _Today, _Refdate_Measure )",
                "    VAR _RefYear        = YEAR ( _Refdate )",
                "    VAR _RefQuarter     = _RefYear * 100 + QUARTER(_Refdate)",
                "    VAR _RefMonth       = _RefYear * 100 + MONTH(_Refdate)",
                "    VAR _RefWeek_EU     = _RefYear * 100 + WEEKNUM(_Refdate, 2)",
                " ",
                "-- Earliest date in the model scope",
                "VAR _EarliestDate       = DATE ( YEAR ( MIN ( 'Orders'[Order Date] ) ) - 2, 1, 1 )",
                "VAR _EarliestDate_Safe  = MIN ( _EarliestDate, DATE ( YEAR ( _Today ) + 1, 1, 1 ) )",
                "",
                "-- Latest date in the model scope",
                "VAR _LatestDate_Safe    = DATE ( YEAR ( _Refdate ) + 2, 12, 1 )",
                "",
                "------------------------------------------",
                "-- Base calendar table",
                "VAR _Base_Calendar      = CALENDAR ( _EarliestDate_Safe, _LatestDate_Safe )",
                "------------------------------------------",
                "",
                "",
                "",
                "------------------------------------------",
                "VAR _IntermediateResult = ",
                "    ADDCOLUMNS ( _Base_Calendar,",
                "",
                "            ------------------------------------------",
                "        \"Calendar Year Number (ie 2021)\",           --|",
                "            YEAR ([Date]),                          --|-- Year",
                "                                                    --|",
                "        \"Calendar Year (ie 2021)\",                  --|",
                "            FORMAT ([Date], \"YYYY\"),                --|",
                "            ------------------------------------------",
                "",
                "            ------------------------------------------",
                "        \"Calendar Quarter Year (ie Q1 2021)\",       --|",
                "            \"Q\" &                                   --|-- Quarter",
                "            CONVERT(QUARTER([Date]), STRING) &      --|",
                "            \" \" &                                   --|",
                "            CONVERT(YEAR([Date]), STRING),          --|",
                "                                                    --|",
                "        \"Calendar Year Quarter (ie 202101)\",        --|",
                "            YEAR([Date]) * 100 + QUARTER([Date]),   --|",
                "                                                    --| ",
                "        \"Calendar Quarter (ie Q1)\",                 --|",
                "            \"Q\" &                                   --|",
                "            CONVERT(QUARTER([Date]), STRING),       --|  ",
                "            ------------------------------------------",
                "",
                "            ------------------------------------------",
                "        \"Calendar Month Year (ie Jan 21)\",          --|",
                "            FORMAT ( [Date], \"MMM YY\" ),            --|-- Month",
                "                                                    --|",
                "        \"Calendar Year Month (ie 202101)\",          --|",
                "            YEAR([Date]) * 100 + MONTH([Date]),     --|",
                "                                                    --|",
                "        \"Calendar Month (ie Jan)\",                  --|",
                "            FORMAT ( [Date], \"MMM\" ),               --|",
                "                                                    --|",
                "        \"Calendar Month # (ie 1)\",                  --|",
                "            MONTH ( [Date] ),                       --|",
                "            ------------------------------------------",
                "            ",
                "            ------------------------------------------",
                "        \"Calendar Week EU (ie WK25)\",               --|",
                "            \"WK\" & WEEKNUM( [Date], 2 ),            --|-- Week",
                "                                                    --|",
                "        \"Calendar Week Number EU (ie 25)\",          --|",
                "            WEEKNUM( [Date], 2 ),                   --|",
                "                                                    --|",
                "        \"Calendar Year Week Number EU (ie 202125)\", --|",
                "            YEAR ( [Date] ) * 100                   --|",
                "            +                                       --|",
                "            WEEKNUM( [Date], 2 ),                   --|",
                "                                                    --|",
                "        \"Calendar Week US (ie WK25)\",               --|",
                "            \"WK\" & WEEKNUM( [Date], 1 ),            --|",
                "                                                    --|",
                "        \"Calendar Week Number US (ie 25)\",          --|",
                "            WEEKNUM( [Date], 1 ),                   --|",
                "                                                    --|",
                "        \"Calendar Year Week Number US (ie 202125)\", --|",
                "            YEAR ( [Date] ) * 100                   --|",
                "            +                                       --|",
                "            WEEKNUM( [Date], 1 ),                   --|",
                "                                                    --|",
                "        \"Calendar Week ISO (ie WK25)\",              --|",
                "            \"WK\" & WEEKNUM( [Date], 21 ),           --|",
                "                                                    --|",
                "        \"Calendar Week Number ISO (ie 25)\",         --|",
                "            WEEKNUM( [Date], 21 ),                  --|",
                "                                                    --|",
                "        \"Calendar Year Week Number ISO (ie 202125)\",--|",
                "            YEAR ( [Date] ) * 100                   --|",
                "            +                                       --|",
                "            WEEKNUM( [Date], 21 ),                  --|",
                "            ------------------------------------------",
                "",
                "            ------------------------------------------",
                "        \"Weekday Short (i.e. Mon)\",                 --|",
                "            FORMAT ( [Date], \"DDD\" ),               --|-- Weekday",
                "                                                    --|",
                "        \"Weekday Name (i.e. Monday)\",               --|",
                "            FORMAT ( [Date], \"DDDD\" ),              --|",
                "                                                    --|",
                "        \"Weekday Number EU (i.e. 1)\",               --|",
                "            WEEKDAY ( [Date], 2 ),                  --|",
                "            ------------------------------------------",
                "            ",
                "            ------------------------------------------",
                "        \"Calendar Month Day (i.e. Jan 05)\",         --|",
                "            FORMAT ( [Date], \"MMM DD\" ),            --|-- Day",
                "                                                    --|",
                "        \"Calendar Month Day (i.e. 0105)\",           --|",
                "            MONTH([Date]) * 100                     --|",
                "            +                                       --|",
                "            DAY([Date]),                            --|",
                "                                                    --|",
                "        \"YYYYMMDD\",                                 --|",
                "            YEAR ( [Date] ) * 10000                 --|",
                "            +                                       --|",
                "            MONTH ( [Date] ) * 100                  --|",
                "            +                                       --|",
                "            DAY ( [Date] ),                         --|",
                "            ------------------------------------------",
                "",
                "",
                "            ------------------------------------------",
                "        \"IsDateInScope\",                            --|",
                "            [Date] <= _Refdate                      --|-- Boolean",
                "            &&                                      --|",
                "            YEAR([Date]) > YEAR(_EarliestDate),     --|",
                "                                                    --|",
                "        \"IsBeforeThisMonth\",                        --|",
                "            [Date] <= EOMONTH ( _Refdate, -1 ),     --|",
                "                                                    --|",
                "        \"IsLastMonth\",                              --|",
                "            [Date] <= EOMONTH ( _Refdate, 0 )       --|",
                "            &&                                      --|",
                "            [Date] > EOMONTH ( _Refdate, -1 ),      --|",
                "                                                    --|",
                "        \"IsYTD\",                                    --|",
                "            MONTH([Date])                           --|",
                "            <=                                      --|",
                "            MONTH(EOMONTH ( _Refdate, 0 )),         --|",
                "                                                    --|",
                "        \"IsActualToday\",                            --|",
                "            [Date] = _Today,                        --|",
                "                                                    --|",
                "        \"IsRefDate\",                                --|",
                "            [Date] = _Refdate,                      --|",
                "                                                    --|",
                "        \"IsHoliday\",                                --|",
                "            MONTH([Date]) * 100                     --|",
                "            +                                       --|",
                "            DAY([Date])                             --|",
                "                IN {0101, 0501, 1111, 1225},        --|",
                "                                                    --|",
                "        \"IsWeekday\",                                --|",
                "            WEEKDAY([Date], 2)                      --|",
                "                IN {1, 2, 3, 4, 5})                 --|",
                "            ------------------------------------------",
                "",
                "VAR _Result = ",
                "    ",
                "            --------------------------------------------",
                "    ADDCOLUMNS (                                      --|",
                "        _IntermediateResult,                          --|-- Boolean #2",
                "        \"IsThisYear\",                                 --|",
                "            [Calendar Year Number (ie 2021)]          --|",
                "                = _RefYear,                           --|",
                "                                                      --|",
                "        \"IsThisMonth\",                                --|",
                "            [Calendar Year Month (ie 202101)]         --|",
                "                = _RefMonth,                          --|",
                "                                                      --|",
                "        \"IsThisQuarter\",                              --|",
                "            [Calendar Year Quarter (ie 202101)]       --|",
                "                = _RefQuarter,                        --|",
                "                                                      --|",
                "        \"IsThisWeek\",                                 --|",
                "            [Calendar Year Week Number EU (ie 202125)]--|",
                "                = _RefWeek_EU                         --|",
                "    )                                                 --|",
                "            --------------------------------------------",
                "            ",
                "RETURN ",
                "    _Result"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "# Workdays in Selected Month",
            "expression": [
              "IF (",
              "    HASONEVALUE ('Date'[Calendar Month Year (ie Jan 21)]),",
              "    CALCULATE (",
              "        MAX ('Date'[Workdays MTD]),",
              "        VALUES ('Date'[Calendar Month Year (ie Jan 21)])",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "55924c9b-cb78-47d3-824e-92cb1a525706"
          },
          {
            "name": "# Workdays in Selected Quarter",
            "expression": [
              "IF (",
              "    HASONEVALUE ('Date'[Calendar Quarter Year (ie Q1 2021)]),",
              "    CALCULATE (",
              "        MAX ('Date'[Workdays QTD]),",
              "        VALUES ('Date'[Calendar Quarter Year (ie Q1 2021)])",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "84ccfbbd-bf7b-43b6-8e35-df7a54d0d9e7"
          },
          {
            "name": "# Workdays in Selected Year",
            "expression": [
              "IF (",
              "    HASONEVALUE ('Date'[Calendar Year (ie 2021)]),",
              "    CALCULATE (",
              "        MAX ('Date'[Workdays YTD]),",
              "        VALUES ('Date'[Calendar Year (ie 2021)])",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "a5eb1c3f-f13e-4d86-9fb2-d7bbb3fc3cf6"
          },
          {
            "name": "# Workdays MTD",
            "expression": [
              "CALCULATE(",
              "    MAX( 'Date'[Workdays MTD] ),",
              "    'Date'[IsDateInScope] = TRUE",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "4b0555ab-6912-4d3c-b613-0d2d542a6965"
          },
          {
            "name": "# Workdays QTD",
            "expression": [
              "CALCULATE(",
              "    MAX( 'Date'[Workdays QTD] ),",
              "    'Date'[IsDateInScope] = TRUE",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "a07fb670-6765-4b8b-91da-3170765e8e94"
          },
          {
            "name": "# Workdays YTD",
            "expression": [
              "CALCULATE(",
              "    MAX( 'Date'[Workdays YTD] ),",
              "    'Date'[IsDateInScope] = TRUE",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "0a27905d-9841-4cda-9976-ec65d16821d4"
          },
          {
            "name": "% Workdays MTD",
            "expression": [
              "IF (",
              "    HASONEVALUE ('Date'[Calendar Month Year (ie Jan 21)]),",
              "    MROUND (",
              "        DIVIDE ([# Workdays MTD], [# Workdays in Selected Month]),",
              "        0.01",
              "    )",
              ")"
            ],
            "formatString": "#,##0%",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "68e3c8f6-6e44-4191-9e86-90afb7ddf261"
          },
          {
            "name": "% Workdays QTD",
            "expression": [
              "IF (",
              "    HASONEVALUE ('Date'[Calendar Quarter Year (ie Q1 2021)]),",
              "    MROUND (",
              "        DIVIDE ([# Workdays QTD], [# Workdays in Selected Quarter]),",
              "        0.01",
              "    )",
              ")"
            ],
            "formatString": "#,##0%",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "7acd41b3-fc3c-4e8b-809c-a5edc09bc853"
          },
          {
            "name": "% Workdays YTD",
            "expression": [
              "IF (",
              "    HASONEVALUE ('Date'[Calendar Year (ie 2021)]),",
              "    MROUND (",
              "        DIVIDE ([# Workdays YTD], [# Workdays in Selected Year]),",
              "        0.01",
              "    )",
              ")"
            ],
            "formatString": "#,##0%",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "74c83d7c-2d91-4dc3-87f3-d129a2b220ae"
          },
          {
            "name": "RefDate",
            "expression": "CALCULATE ( MAX ( 'Invoices'[Billing Date] ), REMOVEFILTERS ( ) )",
            "isHidden": true,
            "displayFolder": "Measures",
            "lineageTag": "75027a89-68f7-4e3f-9d0b-abbb14b92094"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "1748d90b-b004-4b0d-afa9-77214627ce0f",
            "levels": [
              {
                "name": "Calendar Year (ie 2021)",
                "ordinal": 0,
                "column": "Calendar Year (ie 2021)",
                "lineageTag": "ec183b08-c5d1-42ca-a087-e4dbfbcc9349"
              },
              {
                "name": "Calendar Month (ie Jan)",
                "ordinal": 2,
                "column": "Calendar Month (ie Jan)",
                "lineageTag": "7ab92588-0b9b-4b03-a4ee-a556e9b8cc1e"
              },
              {
                "name": "Calendar Quarter (ie Q1)",
                "ordinal": 1,
                "column": "Calendar Quarter (ie Q1)",
                "lineageTag": "54cf79cd-0493-4918-9750-c334dcfe4eb5"
              },
              {
                "name": "Calendar Week EU (ie WK25)",
                "ordinal": 3,
                "column": "Calendar Week EU (ie WK25)",
                "lineageTag": "51e5883b-9124-4ff7-9600-954ef91e6f80"
              },
              {
                "name": "Weekday Short (i.e. Mon)",
                "ordinal": 4,
                "column": "Weekday Short (i.e. Mon)",
                "lineageTag": "5aef54bd-34f0-47c9-b70c-21e5cf59e625"
              },
              {
                "name": "Date",
                "ordinal": 5,
                "column": "Date",
                "lineageTag": "cb95b6f4-85ff-4121-bb82-3e18125ac0db"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Dimension Tables"
          }
        ]
      },
      {
        "name": "Employees",
        "isHidden": true,
        "lineageTag": "524ed7be-f2f0-440f-9280-3b067d6f766e",
        "columns": [
          {
            "name": "Data Security Rule",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Data Security Rule",
            "displayFolder": "Columns",
            "lineageTag": "b08c9506-5704-406c-a5f5-5ea65d6623b8"
          },
          {
            "name": "Employee Email",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Employee Email",
            "displayFolder": "Columns",
            "lineageTag": "e4e18027-3292-4531-9c47-c0d2bd3d8efb"
          },
          {
            "name": "Employee Name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Employee Name",
            "displayFolder": "Columns",
            "lineageTag": "fc711d7b-da3f-4e5e-9c68-0073c2489c1a"
          },
          {
            "name": "Role",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Role",
            "displayFolder": "Columns",
            "lineageTag": "3d1387dd-01f0-4f13-ab38-811f06cd1359"
          }
        ],
        "partitions": [
          {
            "name": "Employees",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SpacePartsDW\",",
                "    Data = Source{[Schema=\"Dimview\",Item=\"Employees\"]}[Data]",
                "in",
                "    Data"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Dimension Tables"
          }
        ]
      },
      {
        "name": "Exchange Rate",
        "lineageTag": "01ee8527-a2dc-471d-9a3d-9ccfe51284ef",
        "columns": [
          {
            "name": "Currency System",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Currency System",
            "displayFolder": "2. Other Currency Fields",
            "lineageTag": "ee01193c-1f42-4aec-a1fc-45db6cabfb80"
          },
          {
            "name": "Currency",
            "dataType": "string",
            "sourceColumn": "From Currency",
            "displayFolder": "1. Select a Currency",
            "lineageTag": "ee8bbaa9-0b3e-42bf-9d01-d907458159bc"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Date",
            "displayFolder": "2. Other Currency Fields",
            "lineageTag": "024862a6-5e54-4cc6-a1d7-2b7b1f393ad6"
          },
          {
            "name": "Exchange Rate Composite Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Exchange Rate Composite Key",
            "displayFolder": "2. Other Currency Fields",
            "lineageTag": "5b3738b3-2625-4510-909a-71dd86316090"
          },
          {
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Month",
            "displayFolder": "2. Other Currency Fields",
            "lineageTag": "fe0e261d-d4be-49a5-b2d0-a644f272b0eb"
          },
          {
            "name": "Rate Type",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Rate Type",
            "displayFolder": "2. Other Currency Fields",
            "lineageTag": "452c5cfd-c704-4b98-be56-71082368b44b"
          },
          {
            "name": "Rate",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "Rate",
            "displayFolder": "2. Other Currency Fields",
            "lineageTag": "c7c98d7b-101b-4fb0-b4b6-a1990adb1ecb"
          },
          {
            "name": "To Currency",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "To Currency",
            "displayFolder": "2. Other Currency Fields",
            "lineageTag": "7640e9c9-9b46-48e7-bdaa-c96bb487b625"
          }
        ],
        "partitions": [
          {
            "name": "Exchange Rate",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SpacePartsDW\",",
                "    Data = Source{[Schema=\"Dimview\",Item=\"Exchange Rate\"]}[Data]",
                "in",
                "    Data"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Dimension Tables"
          }
        ]
      },
      {
        "name": "Forecast",
        "lineageTag": "f44175ec-6e73-4cc5-93db-4febba622528",
        "columns": [
          {
            "name": "Forecast (EUR)",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Forecast (EUR)",
            "displayFolder": "1. Facts",
            "lineageTag": "68c093b8-8ce0-44cc-ab2c-213dcc900077"
          },
          {
            "name": "Month",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Forecast Month",
            "displayFolder": "2. Keys",
            "lineageTag": "1c521f45-cb4d-444a-94da-8684fd62cf37"
          },
          {
            "name": "Product Type",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Product Type",
            "displayFolder": "2. Keys",
            "lineageTag": "a3e38e2f-113c-4b33-97bd-ba68256feaff"
          },
          {
            "name": "Region Territory",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Region Territory",
            "displayFolder": "2. Keys",
            "lineageTag": "864f2700-e020-4b14-98ce-7e5b4154275d"
          }
        ],
        "partitions": [
          {
            "name": "Forecast",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SpacePartsDW\",",
                "    Data = Source{[Schema=\"Factview\",Item=\"Forecast\"]}[Data],",
                "    #\"Select Columns\" = Table.SelectColumns ( Data, {\"Forecast Month\", \"Forecast (EUR)\", \"Region Territory\", \"Product Type\"})",
                "in",
                "    #\"Select Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Forecast MTD vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Forecast MTD]",
              "VAR _DELTA  = [MTD Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "Measures\\ii. MTD",
            "lineageTag": "852154a6-c9a0-46bc-bc2f-f27301426027"
          },
          {
            "name": "Forecast MTD vs. Gross Sales (Δ)",
            "expression": [
              "",
              "[MTD Gross Sales] - [Forecast MTD]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "Measures\\ii. MTD",
            "lineageTag": "32e7cb6e-42b1-4549-ac5a-4dcd6d678b1c"
          },
          {
            "name": "Forecast MTD",
            "expression": [
              "",
              "-- Calculates the target for the current month/year selection",
              "VAR _CURRENT_MONTH_VALUE =",
              "    CALCULATE (",
              "        [Forecast],",
              "        ALL ( 'Date' ),",
              "        VALUES ( 'Date'[Calendar Month Year (ie Jan 21)] )",
              "    ) ",
              "",
              "-- Computes rate at which Forecast increases through the month",
              "VAR _CURRENT_MONTH_PERC_WORKDAYS_MTD =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] ),",
              "            'Date'[IsDateInScope] = TRUE",
              "        ),",
              "        1.035",
              "    )",
              "",
              "VAR _CURRENT_MONTH_PERC_WORKDAYS =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] )",
              "        ),",
              "        1.035",
              "    )",
              "",
              "VAR _PERIOD =",
              "    SELECTEDVALUE (",
              "        '4) Selected Period'[Period]",
              "    )",
              "VAR _HASONEMONTH =",
              "    HASONEVALUE (",
              "        'Date'[Calendar Month Year (ie Jan 21)]",
              "    )",
              "RETURN",
              "    -- return MTD value if a month is selected",
              "    IF.EAGER (",
              "        _HASONEMONTH",
              "            && _PERIOD = \"Full Period\",",
              "        _CURRENT_MONTH_PERC_WORKDAYS",
              "            * _CURRENT_MONTH_VALUE,",
              "",
              "        IF (",
              "            _HASONEMONTH,",
              "            _CURRENT_MONTH_PERC_WORKDAYS_MTD",
              "                * _CURRENT_MONTH_VALUE",
              "        )",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\ii. MTD",
            "lineageTag": "59b4471b-3cce-43f5-ab24-5555faf2bd37"
          },
          {
            "name": "Forecast QTD vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Forecast QTD]",
              "VAR _DELTA  = [Gross Sales] - [Forecast QTD]",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "Measures\\iii. QTD",
            "lineageTag": "5fc59186-997c-4890-a18b-97e7662b0667"
          },
          {
            "name": "Forecast QTD vs. Gross Sales (Δ)",
            "expression": [
              "",
              "[Gross Sales] - [Forecast QTD]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "Measures\\iii. QTD",
            "lineageTag": "86a370f9-61ff-46d1-a054-614a604cf185"
          },
          {
            "name": "Forecast QTD",
            "expression": [
              "",
              "VAR _DATES_QTD =",
              "    CALCULATETABLE (",
              "        DATESQTD ('Date'[Date]),",
              "        'Date'[IsThisMonth] = FALSE",
              "    )",
              "VAR _CURRENT_MONTH_Forecast = [Forecast MTD]",
              "VAR _QTD_Forecast_BEFORE_THIS_MONTH = CALCULATE ([Forecast], _DATES_QTD)",
              "VAR _RESULT = _CURRENT_MONTH_Forecast + _QTD_Forecast_BEFORE_THIS_MONTH",
              "RETURN",
              "    _RESULT"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\iii. QTD",
            "lineageTag": "b016de82-c11c-4231-a206-c2d02568aa7f"
          },
          {
            "name": "Forecast vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Forecast]",
              "VAR _DELTA  = [Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "0f955ab8-28e0-4ac4-b335-23c88440db41"
          },
          {
            "name": "Forecast vs. Gross Sales (Δ)",
            "expression": [
              "",
              "[Gross Sales] - [Forecast]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "68c5bb1f-fa70-42a1-8f9c-34f95ed0950b"
          },
          {
            "name": "Forecast YTD vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Forecast YTD]",
              "VAR _DELTA  = [Gross Sales] - [Forecast YTD]",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "Measures\\iv. YTD",
            "lineageTag": "8d1f9942-e438-4edf-99fb-a244511fb73f"
          },
          {
            "name": "Forecast YTD vs. Gross Sales (Δ)",
            "expression": [
              "",
              "[Gross Sales] - [Forecast YTD]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "Measures\\iv. YTD",
            "lineageTag": "1a4e0d88-e751-4350-bf75-3cb5aab8e7c1"
          },
          {
            "name": "Forecast YTD",
            "expression": [
              "",
              "VAR _DATES_YTD =",
              "    CALCULATETABLE (",
              "        DATESYTD ('Date'[Date]),",
              "        'Date'[IsThisMonth] = FALSE",
              "    )",
              "VAR _CURRENT_MONTH_Forecast = [Forecast MTD]",
              "VAR _QTD_Forecast_BEFORE_THIS_MONTH = CALCULATE ([Forecast], _DATES_YTD)",
              "VAR _RESULT = _CURRENT_MONTH_Forecast + _QTD_Forecast_BEFORE_THIS_MONTH",
              "RETURN",
              "    _RESULT"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\iv. YTD",
            "lineageTag": "8db40d35-8818-45fb-b008-f39e79ba3084"
          },
          {
            "name": "Forecast",
            "expression": [
              "",
              "IF.EAGER(",
              "    HASONEVALUE( '2) Selected Unit'[Select a Unit] )",
              "        && ",
              "    HASONEVALUE( 'Exchange Rate'[Currency] ),",
              "",
              "    VAR _SELECTED_CURRENCY = ",
              "        SELECTEDVALUE( 'Exchange Rate'[Currency] )",
              "",
              "    VAR _SELECTED_RATE_TYPE = ",
              "        SELECTEDVALUE( '2) Selected Unit'[Select a Unit] )",
              "    ",
              "    VAR _SELECTED_BUDGET_RATE =",
              "        MAX( 'Exchange Rate'[Rate] )",
              "        ",
              "    VAR _SELECTED_MONTHLY_RATE =",
              "        ADDCOLUMNS(",
              "            SUMMARIZE(",
              "                'Exchange Rate',",
              "                'Date'[Calendar Month Year (ie Jan 21)]",
              "            ),",
              "            \"Curr\", ",
              "            CALCULATE ( ",
              "                MAX( 'Exchange Rate'[Rate] ) ",
              "            )",
              "        )",
              "        ",
              "    RETURN",
              "",
              "    IF(",
              "        _SELECTED_RATE_TYPE = \"Value (Budget Rate)\",",
              "        SUM ( 'Forecast'[Forecast (EUR)]) ",
              "        * ",
              "        _SELECTED_BUDGET_RATE,",
              "        ",
              "        IF(",
              "            _SELECTED_RATE_TYPE = \"Value (Monthly Rate)\",",
              "            SUMX(",
              "                _SELECTED_MONTHLY_RATE,",
              "                CALCULATE( ",
              "                    SUM ( 'Forecast'[Forecast (EUR)])",
              "                )",
              "                * [Curr]",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "a6383680-00ad-44a2-a972-afd4378179ad"
          },
          {
            "name": "Total Forecast",
            "expression": [
              "",
              "    VAR _SelectedRate = MAX ( 'Exchange Rate'[Rate] )",
              "RETURN",
              "    SUM ( 'Forecast'[Forecast (EUR)] ) * _SelectedRate"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "66dd4eca-8cd0-492a-b93a-0bb91c4f6b04"
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Fact Tables"
          }
        ]
      },
      {
        "name": "Invoice Document Type",
        "lineageTag": "dbcc3ac6-9a34-4dc6-8477-078cb12b3dd4",
        "columns": [
          {
            "name": "Code",
            "dataType": "string",
            "sourceColumn": "Billing Document Type Code",
            "sortByColumn": "Doc. Type Ordinal",
            "displayFolder": "2. Keys",
            "lineageTag": "e9a08be0-7588-41c4-bc84-7d10ed0d5d0f"
          },
          {
            "name": "Doc. Type Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Doc. Type Ordinal",
            "displayFolder": "3. Ordinal",
            "lineageTag": "3439cdad-fc7d-4cfb-9b69-26b03bd3ef65"
          },
          {
            "name": "Group Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Group Ordinal",
            "displayFolder": "3. Ordinal",
            "lineageTag": "5c8de158-176b-43a0-aa9d-5314d4b4ded6"
          },
          {
            "name": "Group",
            "dataType": "string",
            "sourceColumn": "Group",
            "sortByColumn": "Group Ordinal",
            "displayFolder": "1. Billing Doc. Type",
            "lineageTag": "494309fe-449d-447a-9522-5aaac15890e8"
          },
          {
            "name": "Text",
            "dataType": "string",
            "sourceColumn": "Text",
            "sortByColumn": "Doc. Type Ordinal",
            "displayFolder": "1. Billing Doc. Type",
            "lineageTag": "b90274be-9a59-4782-b817-fe6c65a5c0b3"
          }
        ],
        "partitions": [
          {
            "name": "Invoice Document Type",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SpacePartsDW\",",
                "    Data = Source{[Schema=\"Dimview\",Item=\"Invoice Document Type\"]}[Data]",
                "in",
                "    Data"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Dimension Tables"
          }
        ]
      },
      {
        "name": "Invoices",
        "lineageTag": "e864ea7c-38b6-44bc-92b6-e167034b7f19",
        "columns": [
          {
            "name": "Billing Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Billing Date",
            "displayFolder": "Columns\\2. Keys\\Dates",
            "lineageTag": "3ecdddab-f189-4960-9608-28147ac9655e"
          },
          {
            "name": "Billing Document Line Item Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Billing Document Line Item Number",
            "displayFolder": "Columns\\1. Degenerate Dimensions\\Document #s",
            "lineageTag": "2d7bb6a5-1f60-464f-8c26-275762c63277"
          },
          {
            "name": "Billing Document Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Billing Document Number",
            "displayFolder": "Columns\\1. Degenerate Dimensions\\Document #s",
            "lineageTag": "80891c7d-b84a-4f81-b676-701a8560036e"
          },
          {
            "name": "Billing Document Type Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Billing Document Type Code",
            "displayFolder": "Columns\\2. Keys",
            "lineageTag": "f08cfa92-9f3b-4abe-8925-00d00d77d15a"
          },
          {
            "name": "Customer Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Customer Key",
            "displayFolder": "Columns\\2. Keys",
            "lineageTag": "00383e87-df2b-496c-8fa2-6c332eaa6e07"
          },
          {
            "name": "Delivery Cost",
            "dataType": "double",
            "description": "The cost of the delivery only",
            "isHidden": true,
            "sourceColumn": "Delivery Cost",
            "displayFolder": "Columns\\0. Facts",
            "lineageTag": "2cab7bca-6b96-40ec-8270-84d9dd874335",
            "summarizeBy": "none"
          },
          {
            "name": "Freight",
            "dataType": "double",
            "description": "The freight surcharge is what we charge for delivery. It is one of our lines of revenue.",
            "isHidden": true,
            "sourceColumn": "Freight",
            "displayFolder": "Columns\\0. Facts",
            "lineageTag": "86a9f2ce-a05f-4470-9c36-a55196785919",
            "summarizeBy": "none"
          },
          {
            "name": "Late Delivery Penalties",
            "dataType": "double",
            "description": "Late Delivery penalties occur when we fail to meet the SLA for deliveries. If the products take longer than a certain number of days to deliver after the requested delivery date, a Late Delivery Penalty is levied.",
            "isHidden": true,
            "sourceColumn": "Late Delivery Penalties",
            "displayFolder": "Columns\\0. Facts",
            "lineageTag": "63f35167-689e-4bfd-a6d4-d3e6c7b7d6ab",
            "summarizeBy": "none"
          },
          {
            "name": "Local Currency",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Local Currency",
            "displayFolder": "Columns\\2. Keys",
            "lineageTag": "b00f4fb9-8ed5-4972-b62a-352eac69d319"
          },
          {
            "name": "Net Invoice COGS",
            "dataType": "double",
            "description": "All costs associated with the sold product",
            "isHidden": true,
            "sourceColumn": "Net Invoice COGS",
            "displayFolder": "Columns\\0. Facts",
            "lineageTag": "8ac8f0a8-e780-4d46-aaba-a4b806711a51",
            "summarizeBy": "none"
          },
          {
            "name": "Net Invoice Quantity",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Net Invoice Quantity",
            "displayFolder": "Columns\\0. Facts",
            "lineageTag": "5b447336-164e-415f-9d13-759cfa0aa0b5",
            "summarizeBy": "none"
          },
          {
            "name": "Net Invoice Value",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Net Invoice Value",
            "displayFolder": "Columns\\0. Facts",
            "lineageTag": "86af53e2-7af5-497b-b995-9d43aebbc686",
            "summarizeBy": "none"
          },
          {
            "name": "OTD Indicator",
            "dataType": "boolean",
            "isHidden": true,
            "sourceColumn": "OTD Indicator",
            "displayFolder": "Columns\\2. Keys",
            "lineageTag": "61c6d81f-1fb6-420d-a6bf-aaaff17aedcb"
          },
          {
            "name": "Overdue Payment Penalties",
            "dataType": "double",
            "description": "Overdue Payments result when the customer hasn't paid their invoice within a certain number of days since the product was shipped.",
            "isHidden": true,
            "sourceColumn": "Overdue Payment Penalties",
            "displayFolder": "Columns\\0. Facts",
            "lineageTag": "d220b6b9-526e-48f9-bb37-ad55b4911012",
            "summarizeBy": "none"
          },
          {
            "name": "Product Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Product Key",
            "displayFolder": "Columns\\2. Keys",
            "lineageTag": "2206902c-3b4b-4b19-bc0f-a4d1b133f937"
          },
          {
            "name": "Ship Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Ship Date",
            "displayFolder": "Columns\\2. Keys\\Dates",
            "lineageTag": "26b8ed72-1ee8-4732-b37e-89fbcded5bc1"
          },
          {
            "name": "Taxes & Commercial Fees",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Taxes & Commercial Fees",
            "displayFolder": "Columns\\0. Facts",
            "lineageTag": "87bf78e5-838d-4135-8088-d1ab84900b17",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Invoices",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SpacePartsDW\",",
                "    Data = Source{[Schema=\"Factview\",Item=\"Invoices\"]}[Data],",
                "    #\"Select Columns\" = Table.RemoveColumns ( Data, {\"DWCreatedDate\", \"Net Invoice Cost\"} )",
                "in",
                "    #\"Select Columns\"",
                "// Test"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Delivery Margin (%)",
            "description": "The delivery margin only considers the revenue and costs associated with freights, delivery and shipments.",
            "expression": [
              "",
              "VAR _TOTAL =",
              "    CALCULATE (",
              "        [Total Freight Surcharge],",
              "        'Invoice Document Type'[Code] IN {\"invoice\", \"express\"}",
              "    )",
              "VAR _MARGIN = [Delivery Margin (Value)]",
              "RETURN",
              "    DIVIDE (_MARGIN, _TOTAL)"
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\III. Delivery Margin\\%",
            "lineageTag": "a73f149d-9253-4bcf-851d-5b9e640b297a"
          },
          {
            "name": "Delivery Margin (Value)",
            "description": "The delivery margin only considers the revenue and costs associated with freights, delivery and shipments.",
            "expression": [
              "CALCULATE (",
              "    SUMX (",
              "        'Invoices',",
              "        'Invoices'[Freight] - 'Invoices'[Delivery Cost]",
              "    ),",
              "    'Invoice Document Type'[Code] IN { \"invoice\", \"express\" }",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\III. Delivery Margin\\$",
            "lineageTag": "a3df7f3e-8776-49e2-b3a6-2c1ab3d3d7d4"
          },
          {
            "name": "Delivery Margin 1YP (%)",
            "description": "The delivery margin only considers the revenue and costs associated with freights, delivery and shipments.",
            "expression": [
              "CALCULATE (",
              "    [Delivery Margin (%)],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ")"
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\III. Delivery Margin\\%",
            "lineageTag": "51a2c2de-d360-46e9-8101-6436b464446e"
          },
          {
            "name": "Delivery Margin 1YP (Value)",
            "description": "The delivery margin only considers the revenue and costs associated with freights, delivery and shipments.",
            "expression": [
              "CALCULATE (",
              "    [Delivery Margin (Value)],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\III. Delivery Margin\\$",
            "lineageTag": "d389d9e3-7e22-4c83-9b22-0432663d9ad4"
          },
          {
            "name": "Delivery Margin 2YP (%)",
            "description": "The delivery margin only considers the revenue and costs associated with freights, delivery and shipments.",
            "expression": [
              "CALCULATE (",
              "    [Delivery Margin (%)],",
              "    DATEADD ('Date'[Date], -2, YEAR)",
              ")"
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\III. Delivery Margin\\%",
            "lineageTag": "7e0ecb6b-5ab8-479b-8488-4035f9ecd8c8"
          },
          {
            "name": "Delivery Margin 2YP (Value)",
            "description": "The delivery margin only considers the revenue and costs associated with freights, delivery and shipments.",
            "expression": [
              "CALCULATE (",
              "    [Delivery Margin (Value)],",
              "    DATEADD ('Date'[Date], -2, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\III. Delivery Margin\\$",
            "lineageTag": "ececfa33-1493-4dc5-9b1d-aec2323b1dde"
          },
          {
            "name": "Gross Sales (Quantity)",
            "expression": [
              "",
              "[Total Net Invoice Quantity]"
            ],
            "formatString": "#,##0",
            "displayFolder": "2. Quantity\\b. Gross Sales Actuals",
            "lineageTag": "fbbe4f44-1baf-4dcb-a48b-bd778299ac0c"
          },
          {
            "name": "Gross Sales (Selected Unit)",
            "expression": [
              "",
              "-- Sideways recursion",
              "CALCULATE (",
              "    [Actuals],",
              "    ALL ( '1) Selected Metric'[Select a Measure] ),",
              "    '1) Selected Metric'[Select a Measure] = \"Gross Sales\"",
              ")"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\I. Total",
            "lineageTag": "4abd191a-dbd5-4f11-8333-490f5e6261d3"
          },
          {
            "name": "Gross Sales 1YP (Quantity)",
            "expression": [
              "",
              "CALCULATE (",
              "    [Gross Sales (Quantity)],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "2. Quantity\\b. Gross Sales Actuals",
            "lineageTag": "1a88795e-98d9-4448-96e3-ae142a213826"
          },
          {
            "name": "Gross Sales 1YP",
            "expression": [
              "",
              "CALCULATE (",
              "    [Gross Sales],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\II. 1YP\\Daily",
            "lineageTag": "4a536a45-c2cb-458b-ac8a-a91d10907131"
          },
          {
            "name": "Gross Sales 2YP",
            "expression": [
              "",
              "CALCULATE (",
              "    [Gross Sales],",
              "    DATEADD ('Date'[Date], -2, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\III. 2YP\\Daily",
            "lineageTag": "b88a2169-7b58-45d0-a9ee-a47ff018d763"
          },
          {
            "name": "Gross Sales vs 1YP (%)",
            "expression": [
              "",
              "VAR _TARGET = [Gross Sales 1YP]",
              "VAR _DELTA  = [Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\II. 1YP\\Daily",
            "lineageTag": "a75dd21d-b0da-40ec-904c-5def988c59bf"
          },
          {
            "name": "Gross Sales vs 1YP (Δ)",
            "expression": [
              "",
              "[Gross Sales] - [Gross Sales 1YP]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\II. 1YP\\Daily",
            "lineageTag": "97214fd4-16db-4833-b689-604cab9b320a"
          },
          {
            "name": "Gross Sales vs 2YP (%)",
            "expression": [
              "",
              "VAR _TARGET = [Gross Sales 2YP]",
              "VAR _DELTA  = [Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\III. 2YP\\Daily",
            "lineageTag": "fcc2edfe-b93d-48d2-85e2-cd6a75a802ed"
          },
          {
            "name": "Gross Sales vs 2YP (Δ)",
            "expression": [
              "",
              "[Gross Sales] - [Gross Sales 2YP]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\III. 2YP\\Daily",
            "lineageTag": "c14efb49-8720-4a3e-bdf2-58bda5900a61"
          },
          {
            "name": "Gross Sales",
            "expression": [
              "",
              "[Total Net Invoice Value]",
              "    + [Total Freight Surcharge]",
              "    + [Total Late Delivery Penalties]",
              "    + [Total Overdue Payment Penalties]",
              "    - [Total Taxes & Commercial Fees]"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\I. Total",
            "lineageTag": "741a58cc-9e5b-468e-b0ff-026d0609694a"
          },
          {
            "name": "Invoice Lines",
            "expression": [
              "",
              "COUNTROWS ( 'Invoices' )"
            ],
            "formatString": "#,##0",
            "displayFolder": "3. Lines",
            "lineageTag": "0fab4eac-d56c-45a6-a5c8-8c3ceb38ba83"
          },
          {
            "name": "MTD Gross Sales 1YP",
            "expression": [
              "",
              "-- Calculates Target for the current month/year selection",
              "VAR _CurrentMonth =",
              "    CALCULATE (",
              "        [Gross Sales 1YP],",
              "        ALL ( 'Date' ),",
              "        VALUES (",
              "            'Date'[Calendar Month Year (ie Jan 21)]",
              "        )",
              "    )",
              "",
              "-- Computes rate at which Target increases through the month",
              "VAR _CurrentMonthWDMTD =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] ),",
              "            'Date'[IsDateInScope] = TRUE",
              "        ),",
              "        0.93",
              "    )",
              "VAR _CurrentMonthWDTotal =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] )",
              "        ),",
              "        0.93",
              "    )",
              "VAR _Period =",
              "    SELECTEDVALUE (",
              "        '4) Selected Period'[Period]",
              "    )",
              "VAR _HasOneMonth =",
              "    HASONEVALUE (",
              "        'Date'[Calendar Month Year (ie Jan 21)]",
              "    )",
              "RETURN",
              "    -- return MTD value if a month is selected",
              "    IF.EAGER (",
              "        _HasOneMonth && _Period = \"Full Period\",",
              "        _CurrentMonthWDTotal",
              "            * _CurrentMonth,",
              "        IF (",
              "            _HasOneMonth,",
              "            _CurrentMonthWDMTD",
              "                * _CurrentMonth",
              "        )",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\II. 1YP\\MTD",
            "lineageTag": "bdc0e65f-71dc-4bf5-9133-1bdd49db9459"
          },
          {
            "name": "MTD Gross Sales 2YP",
            "expression": [
              "",
              "-- Calculates Target for the current month/year selection",
              "VAR _CurrentMonth =",
              "    CALCULATE (",
              "        [Gross Sales 2YP],",
              "        ALL ( 'Date' ),",
              "        VALUES (",
              "            'Date'[Calendar Month Year (ie Jan 21)]",
              "        )",
              "    )",
              "",
              "-- Computes rate at which Target increases through the month",
              "VAR _CurrentMonthWDMTD =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] ),",
              "            'Date'[IsDateInScope] = TRUE",
              "        ),",
              "        0.93",
              "    )",
              "VAR _CurrentMonthWDTotal =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] )",
              "        ),",
              "        0.93",
              "    )",
              "VAR _Period =",
              "    SELECTEDVALUE (",
              "        '4) Selected Period'[Period]",
              "    )",
              "VAR _HasOneMonth =",
              "    HASONEVALUE (",
              "        'Date'[Calendar Month Year (ie Jan 21)]",
              "    )",
              "RETURN",
              "    -- return MTD value if a month is selected",
              "    IF.EAGER (",
              "        _HasOneMonth && _Period = \"Full Period\",",
              "        _CurrentMonthWDTotal",
              "            * _CurrentMonth,",
              "        IF (",
              "            _HasOneMonth,",
              "            _CurrentMonthWDMTD",
              "                * _CurrentMonth",
              "        )",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\III. 2YP\\MTD",
            "lineageTag": "90dd4c04-1792-4b14-bfa4-db913f902c84"
          },
          {
            "name": "MTD Gross Sales vs 1YP (%)",
            "expression": [
              "",
              "VAR _TARGET = [MTD Gross Sales 1YP]",
              "VAR _DELTA  = [MTD Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\II. 1YP\\MTD",
            "lineageTag": "ad8d60da-77d9-4feb-9b69-4844c914570a"
          },
          {
            "name": "MTD Gross Sales vs 1YP (Δ)",
            "expression": [
              "",
              "[MTD Gross Sales] - [MTD Gross Sales 1YP]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\II. 1YP\\MTD",
            "lineageTag": "040e8188-aefc-4d20-8d79-fbd5e398d7f9"
          },
          {
            "name": "MTD Gross Sales vs 2YP (%)",
            "expression": [
              "",
              "VAR _TARGET = [MTD Gross Sales 1YP]",
              "VAR _DELTA  = [MTD Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\III. 2YP\\MTD",
            "lineageTag": "490afe1c-f53d-4f28-b54a-aa9d3644619d"
          },
          {
            "name": "MTD Gross Sales vs. 2YP (Δ)",
            "expression": [
              "",
              "[MTD Gross Sales] - [MTD Gross Sales 1YP]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\III. 2YP\\MTD",
            "lineageTag": "980aa9b6-4850-47d2-9af5-daca1b916c0b"
          },
          {
            "name": "MTD Gross Sales",
            "expression": [
              "",
              "CALCULATE (",
              "    [Gross Sales],",
              "    CALCULATETABLE (",
              "        DATESMTD ('Date'[Date]),",
              "        'Date'[IsDateInScope]",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\I. Total",
            "lineageTag": "f1a80b6e-88c7-4b8e-bf9d-98930d82753b"
          },
          {
            "name": "Net Sales 1YP",
            "expression": [
              "",
              "CALCULATE (",
              "    [Net Sales],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\c. Net Sales",
            "lineageTag": "20a7d43c-73f8-4b35-a8de-12ce6a8a39bb"
          },
          {
            "name": "Net Sales 2YP",
            "expression": [
              "",
              "CALCULATE (",
              "    [Net Sales],",
              "    DATEADD ('Date'[Date], -2, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\c. Net Sales",
            "lineageTag": "72b26f0b-1dd5-4f86-85f9-f31cd4be4eaf"
          },
          {
            "name": "Net Sales",
            "expression": [
              "",
              "VAR _RATE = MAX ('Exchange Rate'[Rate])",
              "RETURN",
              "    CALCULATE (",
              "",
              "        -- Convert to common currency (WAT)",
              "        SUMX (",
              "            'Invoices',",
              "",
              "            -- Net sales",
              "            ('Invoices'[Net Invoice Value]",
              "                + 'Invoices'[Freight]",
              "                - 'Invoices'[Taxes & Commercial Fees]",
              "                + 'Invoices'[Late Delivery Penalties]",
              "                + 'Invoices'[Overdue Payment Penalties] )",
              "",
              "                / RELATED ('Budget Rate'[Rate])",
              "        )",
              "",
              "            -- Convert to selected currency",
              "            * _RATE,",
              "",
              "        -- Limit to dates in scope",
              "        'Date'[IsDateInScope] = TRUE",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\c. Net Sales",
            "lineageTag": "d419fc83-48b7-4f13-9c8c-b8895cc702f8"
          },
          {
            "name": "Selling Margin (%)",
            "description": "The selling margin is the margin earned when considering only the revenue and costs associated with the product, before delivery",
            "expression": [
              "VAR _TOTAL =",
              "    CALCULATE (",
              "        [Total Net Invoice Value],",
              "        'Invoice Document Type'[Code] = \"invoice\"",
              "    )",
              "VAR _MARGIN = [Selling Margin (Value)]",
              "RETURN",
              "    DIVIDE (_MARGIN, _TOTAL)"
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\II. Selling Margin\\%",
            "lineageTag": "694fb860-b402-4f79-8f97-8183decf7b9c"
          },
          {
            "name": "Selling Margin (Value)",
            "description": "The selling margin is the margin earned when considering only the revenue and costs associated with the product, before delivery",
            "expression": [
              "",
              "CALCULATE (",
              "    SUMX (",
              "        'Invoices',",
              "        'Invoices'[Net Invoice Value] - 'Invoices'[Net Invoice COGS]",
              "    ),",
              "    'Invoice Document Type'[Code] = \"invoice\"",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\II. Selling Margin\\$",
            "lineageTag": "1cc24634-fea9-4285-b3b6-250e53d2007f"
          },
          {
            "name": "Selling Margin 1YP (%)",
            "description": "The selling margin is the margin earned when considering only the revenue and costs associated with the product, before delivery",
            "expression": [
              "CALCULATE (",
              "    [Selling Margin (%)],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ") "
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\II. Selling Margin\\%",
            "lineageTag": "bef507ae-f42d-4db8-a946-98e2763be001"
          },
          {
            "name": "Selling Margin 1YP (Value)",
            "description": "The selling margin is the margin earned when considering only the revenue and costs associated with the product, before delivery",
            "expression": [
              "CALCULATE (",
              "    [Selling Margin (Value)],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\II. Selling Margin\\$",
            "lineageTag": "f68650bc-c863-4091-bb0e-392f6b60dfb7"
          },
          {
            "name": "Selling Margin 2YP (%)",
            "description": "The selling margin is the margin earned when considering only the revenue and costs associated with the product, before delivery",
            "expression": [
              "CALCULATE (",
              "    [Selling Margin (%)],",
              "    DATEADD ('Date'[Date], -2, YEAR)",
              ") "
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\II. Selling Margin\\%",
            "lineageTag": "e0755da1-9238-4c67-8223-7e56d5e6a565"
          },
          {
            "name": "Selling Margin 2YP (Value)",
            "description": "The selling margin is the margin earned when considering only the revenue and costs associated with the product, before delivery",
            "expression": [
              "CALCULATE (",
              "    [Selling Margin (Value)],",
              "    DATEADD ('Date'[Date], -2, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\II. Selling Margin\\$",
            "lineageTag": "c21e4cf6-6405-44fc-af73-e7293dce81b2"
          },
          {
            "name": "Standard Margin (%)",
            "description": [
              "The standard margin is the selling margin + the delivery margin",
              "It takes into account all revenues and costs."
            ],
            "expression": [
              "",
              "DIVIDE ( [Standard Margin (Value)], [Net Sales] ) "
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\I. Std. Margin\\%",
            "lineageTag": "4c61bc8f-205a-46d6-b453-73ca8d84dfa9"
          },
          {
            "name": "Standard Margin (Value)",
            "description": [
              "The standard margin is the selling margin + the delivery margin",
              "It takes into account all revenues and costs."
            ],
            "expression": [
              "",
              "VAR _RATE = MAX ('Exchange Rate'[Rate])",
              "RETURN",
              "    CALCULATE (",
              "",
              "        -- Convert to common currency (WAT)",
              "        SUMX (",
              "            'Invoices',",
              "",
              "            -- Net Sales",
              "            VAR _NET = ",
              "            ('Invoices'[Net Invoice Value]",
              "                + 'Invoices'[Freight]",
              "                - 'Invoices'[Taxes & Commercial Fees]",
              "                + 'Invoices'[Late Delivery Penalties]",
              "                + 'Invoices'[Overdue Payment Penalties] )",
              "",
              "            -- COGS",
              "            VAR _COST =",
              "            ('Invoices'[Net Invoice COGS] ",
              "                + 'Invoices'[Delivery Cost] )",
              "",
              "            RETURN",
              "",
              "            ( _NET - _COST ) / RELATED ('Budget Rate'[Rate])",
              "        )",
              "",
              "            -- Convert to selected rate",
              "            * _RATE,",
              "",
              "        -- Limit to dates in scope",
              "        'Date'[IsDateInScope] = TRUE",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\I. Std. Margin\\$",
            "lineageTag": "3a222bf0-8e75-4c34-9aca-772b56479401"
          },
          {
            "name": "Standard Margin 1YP (%)",
            "description": [
              "The standard margin is the selling margin + the delivery margin",
              "It takes into account all revenues and costs."
            ],
            "expression": [
              "CALCULATE (",
              "    [Standard Margin (%)],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ") "
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\I. Std. Margin\\%",
            "lineageTag": "8ac65e1d-2d6a-4349-a650-c85268850e8e"
          },
          {
            "name": "Standard Margin 1YP (Value)",
            "description": [
              "The standard margin is the selling margin + the delivery margin",
              "It takes into account all revenues and costs."
            ],
            "expression": [
              "CALCULATE (",
              "    [Standard Margin (Value)],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\I. Std. Margin\\$",
            "lineageTag": "a9cdd860-eb00-445f-94e7-0a60ed689b5f"
          },
          {
            "name": "Standard Margin 2YP (%)",
            "description": [
              "The standard margin is the selling margin + the delivery margin",
              "It takes into account all revenues and costs."
            ],
            "expression": [
              "CALCULATE (",
              "    [Standard Margin (%)],",
              "    DATEADD ('Date'[Date], -2, YEAR)",
              ") "
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\I. Std. Margin\\%",
            "lineageTag": "a5db574d-36b4-4e49-b9bb-fb458e2609f4"
          },
          {
            "name": "Standard Margin 2YP (Value)",
            "description": [
              "The standard margin is the selling margin + the delivery margin",
              "It takes into account all revenues and costs."
            ],
            "expression": [
              "CALCULATE (",
              "    [Standard Margin (Value)],",
              "    DATEADD ('Date'[Date], -2, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\I. Std. Margin\\$",
            "lineageTag": "8227c60e-14af-47f2-ae3d-2a0fd213aca0"
          },
          {
            "name": "Total Cost",
            "description": "The cost of the product sold and the shipment / delivery",
            "expression": [
              "",
              "VAR _RATE = MAX ('Exchange Rate'[Rate])",
              "RETURN",
              "    CALCULATE (",
              "",
              "        -- Convert to common currency (WAT)",
              "        SUMX (",
              "            'Invoices',",
              "",
              "            -- COGS",
              "            ('Invoices'[Net Invoice COGS] + 'Invoices'[Delivery Cost])",
              "                / RELATED ('Budget Rate'[Rate])",
              "        )",
              "",
              "            -- Convert to selected currency",
              "            * _RATE,",
              "",
              "        -- Limit to dates in scope",
              "        'Date'[IsDateInScope] = TRUE",
              "    )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\I. Cost",
            "lineageTag": "95ed0ab0-62c3-4932-b3ca-f95d3c94d885"
          },
          {
            "name": "Total Delivery Cost",
            "description": "The cost of the delivery only",
            "expression": [
              "SUMX (",
              "    'Invoices',",
              "    'Invoices'[Delivery Cost]",
              "        / RELATED ( 'Budget Rate'[Rate] )",
              ")",
              "    * MAX ( 'Exchange Rate'[Rate] )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\I. Cost",
            "lineageTag": "943b46c3-96b0-4052-8255-18c5bc1cbd1c"
          },
          {
            "name": "Total Fees & Penalties",
            "expression": [
              "",
              "VAR _RATE = MAX ('Exchange Rate'[Rate])",
              "RETURN",
              "    CALCULATE (",
              "",
              "        -- Convert to common currency (WAT)",
              "        SUMX (",
              "            'Invoices',",
              "",
              "            -- Total fees & penalties",
              "            ('Invoices'[Late Delivery Penalties]",
              "                + 'Invoices'[Overdue Payment Penalties]",
              "                - 'Invoices'[Taxes & Commercial Fees])",
              "",
              "                / RELATED ('Budget Rate'[Rate])",
              "        )",
              "",
              "            -- Convert to selected currency",
              "            * _RATE,",
              "",
              "        -- Limit to dates in scope",
              "        'Date'[IsDateInScope] = TRUE",
              "    )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\II. Penalties and Adjustments",
            "lineageTag": "b4e9e3f7-685d-423c-97d9-bd93ba066c86"
          },
          {
            "name": "Total Freight Surcharge",
            "description": "The freight surcharge is what we charge for delivery. It is one of our lines of revenue.",
            "expression": [
              "",
              "VAR _RATE = MAX ('Exchange Rate'[Rate])",
              "RETURN",
              "    CALCULATE (",
              "",
              "        -- Convert to common currency (WAT)",
              "        SUMX (",
              "            'Invoices',",
              "            'Invoices'[Freight]",
              "                / RELATED ('Budget Rate'[Rate])",
              "        )",
              "",
              "            -- Convert to selected currency",
              "            * _RATE,",
              "",
              "        -- Limit to dates in scope",
              "        'Date'[IsDateInScope] = TRUE",
              "    )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\III. Freight",
            "lineageTag": "5b868e2f-96ad-474a-af98-f0019353dfa6"
          },
          {
            "name": "Total Late Delivery Penalties",
            "description": "Late Delivery penalties occur when we fail to meet the SLA for deliveries. If the products take longer than a certain number of days to deliver after the requested delivery date, a Late Delivery Penalty is levied.",
            "expression": [
              "SUMX (",
              "    'Invoices',",
              "    'Invoices'[Late Delivery Penalties]",
              "        / RELATED ( 'Budget Rate'[Rate] )",
              ")",
              "    * MAX ( 'Exchange Rate'[Rate] )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\II. Penalties and Adjustments",
            "lineageTag": "bd17c83e-b0af-4eca-82b0-030200f60797"
          },
          {
            "name": "Total Net Invoice COGS",
            "description": "All costs associated with the sold product",
            "expression": [
              "SUMX (",
              "    'Invoices',",
              "    'Invoices'[Net Invoice COGS]",
              "        / RELATED ( 'Budget Rate'[Rate] )",
              ")",
              "    * MAX ( 'Exchange Rate'[Rate] )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\I. Cost",
            "lineageTag": "84c05499-4336-4083-8cbc-727b54623304"
          },
          {
            "name": "Total Net Invoice Quantity",
            "description": "This measure is theSumof column 'Invoices'[Net Invoice Quantity]",
            "expression": "SUM ( 'Invoices'[Net Invoice Quantity] )",
            "formatString": "#,##0",
            "displayFolder": "2. Quantity\\b. Gross Sales Actuals",
            "lineageTag": "a7251a86-5e2f-48a9-a417-1e04cbd4345a"
          },
          {
            "name": "Total Net Invoice Value",
            "description": "This measure is theSumof column 'Invoices'[Net Invoice Value]",
            "expression": [
              "SUMX (",
              "    'Invoices',",
              "    'Invoices'[Net Invoice Value]",
              "        / RELATED ( 'Budget Rate'[Rate] )",
              ")",
              "    * MAX ( 'Exchange Rate'[Rate] )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\I. Total",
            "lineageTag": "6f974cef-44fe-4729-9be7-72e3c536185f"
          },
          {
            "name": "Total Overdue Payment Penalties",
            "description": "Overdue Payments result when the customer hasn't paid their invoice within a certain number of days since the product was shipped.",
            "expression": [
              "SUMX (",
              "    'Invoices',",
              "    'Invoices'[Overdue Payment Penalties]",
              "        / RELATED ( 'Budget Rate'[Rate] )",
              ")",
              "    * MAX ( 'Exchange Rate'[Rate] )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\II. Penalties and Adjustments",
            "lineageTag": "2346db3b-3df1-4c55-a829-bc2ad4b48249"
          },
          {
            "name": "Total Taxes & Commercial Fees",
            "description": "This measure is theSumof column 'Invoices'[Taxes & Commercial Fees]",
            "expression": [
              "SUMX (",
              "    'Invoices',",
              "    'Invoices'[Taxes & Commercial Fees]",
              "        / RELATED ( 'Budget Rate'[Rate] )",
              ")",
              "    * MAX ( 'Exchange Rate'[Rate] )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\II. Penalties and Adjustments",
            "lineageTag": "70b01148-6161-4220-b6f7-c31e996eedfa"
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Fact Tables"
          }
        ]
      },
      {
        "name": "Last Refresh",
        "isHidden": true,
        "lineageTag": "c092152e-6a12-4994-9b22-f31508fed4d6",
        "columns": [
          {
            "name": "Last Refresh",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Last Refresh",
            "isAvailableInMdx": false,
            "displayFolder": "Columns",
            "lineageTag": "0d8cea1e-8072-41a7-a758-85bfde90a435"
          }
        ],
        "partitions": [
          {
            "name": "Last Refresh",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = DateTimeZone.FixedLocalNow()",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Last Refresh Date",
            "expression": "FORMAT ( MAX ( 'Last Refresh'[Last Refresh] ), \"MMM DD, HH:MM\" )",
            "formatString": "MMM DD hh:mm",
            "lineageTag": "bf435c31-2e11-430b-bbe5-c7faee118127"
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Static Tables"
          }
        ]
      },
      {
        "name": "On-Time Delivery",
        "lineageTag": "fa6fb917-28ce-4d34-97ad-9fff4d086e1c",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "OTD Indicator",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Invoices[OTD Indicator]",
            "sortByColumn": "OTD Sort Order",
            "displayFolder": "Columns\\2. Keys",
            "lineageTag": "705b4fb2-c9bb-4915-8cb4-b7dac943d875"
          },
          {
            "type": "calculatedTableColumn",
            "name": "OTD Sort Order",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[OTD Sort Order]",
            "displayFolder": "Columns\\3. Ordinal",
            "lineageTag": "7a38eab2-031b-4605-9352-d562e2c842c7"
          },
          {
            "type": "calculatedTableColumn",
            "name": "OTD Status",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[OTD Status]",
            "sortByColumn": "OTD Sort Order",
            "displayFolder": "Columns\\1. OTD",
            "lineageTag": "7f04b315-56ac-43ca-ad33-ff6229fe4e8c"
          }
        ],
        "partitions": [
          {
            "name": "On-Time Delivery",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "ADDCOLUMNS (",
                "    FILTER (",
                "        DISTINCT ('Invoices'[OTD Indicator]),",
                "        NOT ISBLANK ('Invoices'[OTD Indicator])",
                "    ),",
                "    \"OTD Status\",",
                "        SWITCH (",
                "            TRUE (),",
                "            'Invoices'[OTD Indicator] = TRUE, \"On Time\",",
                "            \"Late\"",
                "        ),",
                "    \"OTD Sort Order\",",
                "        SWITCH (",
                "            TRUE (),",
                "            'Invoices'[OTD Indicator] = TRUE, 1,",
                "            2",
                "        )",
                ")"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "OTD % (Lines)",
            "expression": [
              "",
              "VAR _OnTime = [OTD (Lines)]",
              "VAR _Total = CALCULATE (",
              "    [Invoice Lines],",
              "    'Invoice Document Type'[Group] = \"Invoice\"",
              ")",
              "RETURN",
              "",
              "DIVIDE ( _OnTime, _Total )"
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "3. Lines",
            "lineageTag": "ac99485b-fc61-474e-a30e-d0889efce03f"
          },
          {
            "name": "OTD % (Quantity)",
            "expression": [
              "",
              "VAR _OnTime = [OTD (Quantity)]",
              "VAR _Total = ",
              "    CALCULATE (",
              "        [Total Net Invoice Quantity],",
              "        'Invoice Document Type'[Group] = \"Invoice\"",
              "    )",
              "RETURN",
              "",
              "DIVIDE ( _OnTime, _Total )"
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "2. Quantity",
            "lineageTag": "29fcb593-54b0-4061-ae46-2683f72fe75a"
          },
          {
            "name": "OTD % (Value)",
            "expression": [
              "",
              "VAR _OnTime = [OTD (Value)]",
              "VAR _Total = ",
              "    CALCULATE (",
              "        [Total Net Invoice Value],",
              "        'Invoice Document Type'[Group] = \"Invoice\"",
              "    )",
              "RETURN",
              "",
              "DIVIDE ( _OnTime, _Total )"
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value",
            "lineageTag": "8e11165d-306e-4e59-b549-fc1cdf4b080f"
          },
          {
            "name": "OTD (Lines)",
            "expression": [
              "",
              "CALCULATE (",
              "    [Invoice Lines],",
              "    'On-Time Delivery'[OTD Indicator] = TRUE,",
              "    'Invoice Document Type'[Group] = \"Invoice\"",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "3. Lines",
            "lineageTag": "e117a7f4-cf4b-4ec6-80bb-a1cc7970da51"
          },
          {
            "name": "OTD (Quantity)",
            "expression": [
              "",
              "CALCULATE (",
              "    [Total Net Invoice Quantity],",
              "    'On-Time Delivery'[OTD Indicator] = TRUE,",
              "    'Invoice Document Type'[Group] = \"Invoice\"",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "2. Quantity",
            "lineageTag": "7018a9c2-01fc-4f2b-8312-80c684c99e25"
          },
          {
            "name": "OTD (Value)",
            "expression": [
              "",
              "CALCULATE (",
              "    [Total Net Invoice Value],",
              "    'On-Time Delivery'[OTD Indicator] = TRUE,",
              "    'Invoice Document Type'[Group] = \"Invoice\"",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value",
            "lineageTag": "c6c32721-002f-444e-8c7a-dadc8ea6c9c6"
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Dimension Tables"
          }
        ]
      },
      {
        "name": "Order Document Type",
        "lineageTag": "8f2bc030-d173-42c1-9fc4-26bdc4efcbca",
        "columns": [
          {
            "name": "Doc. Type Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Doc. Type Ordinal",
            "displayFolder": "3. Ordinal",
            "lineageTag": "f010755d-dc7c-4add-8bfd-a679f33ef0e5"
          },
          {
            "name": "Group Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Group Ordinal",
            "displayFolder": "3. Ordinal",
            "lineageTag": "1ce7a8e9-fe9f-4c9e-b106-4464b5c9419d"
          },
          {
            "name": "Group",
            "dataType": "string",
            "sourceColumn": "Group",
            "displayFolder": "1. Order Doc. Type",
            "lineageTag": "f6aaeee2-b14c-47b1-9658-cdf317f44195"
          },
          {
            "name": "Sales Order Document Type Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sales Order Document Type Code",
            "displayFolder": "2. Keys",
            "lineageTag": "3370b74d-45ca-4aee-9dfa-3578ad1b476f"
          },
          {
            "name": "Text",
            "dataType": "string",
            "sourceColumn": "Text",
            "displayFolder": "1. Order Doc. Type",
            "lineageTag": "dd298654-70aa-4357-a16e-7cf6eebe5e0f"
          }
        ],
        "partitions": [
          {
            "name": "Order Document Type",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SpacePartsDW\",",
                "    Data = Source{[Schema=\"Dimview\",Item=\"Order Document Type\"]}[Data]",
                "in",
                "    Data"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Dimension Tables"
          }
        ]
      },
      {
        "name": "Order Status",
        "lineageTag": "12d7ff4e-91a1-4a12-bdaa-8138019fc2d0",
        "columns": [
          {
            "name": "Group",
            "dataType": "string",
            "sourceColumn": "Order Status Group",
            "sortByColumn": "Order Status Grouping Ordinal",
            "displayFolder": "1. Order Status",
            "lineageTag": "f34f646d-9d85-473b-be9a-0fd08df3cb97"
          },
          {
            "name": "Order Status Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Order Status Code",
            "sortByColumn": "Order Status Ordinal",
            "displayFolder": "2. Keys",
            "lineageTag": "a100afe0-dcbd-4d7c-99d8-a75db4331ab8"
          },
          {
            "name": "Order Status Grouping Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Order Status Grouping Ordinal",
            "displayFolder": "3. Ordinal",
            "lineageTag": "b6d344fc-1b71-4459-90fc-67a8d9d92e9f"
          },
          {
            "name": "Order Status Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Order Status Ordinal",
            "displayFolder": "3. Ordinal",
            "lineageTag": "d641dd45-15cd-45fa-9d89-069004a9392c"
          },
          {
            "name": "Text",
            "dataType": "string",
            "sourceColumn": "Order Status Text",
            "sortByColumn": "Order Status Ordinal",
            "displayFolder": "1. Order Status",
            "lineageTag": "cac50369-1d71-44df-9a3a-852a8da9d08f"
          }
        ],
        "partitions": [
          {
            "name": "Order Status",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SpacePartsDW\",",
                "    Data = Source{[Schema=\"Dimview\",Item=\"Order Status\"]}[Data]",
                "in",
                "    Data"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Dimension Tables"
          }
        ]
      },
      {
        "name": "Orders",
        "lineageTag": "85791d56-7571-4870-ac91-2e53ef43e591",
        "columns": [
          {
            "name": "Billing Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Billing Date",
            "displayFolder": "Columns\\3. Keys\\Dates",
            "lineageTag": "0dfc4547-ab35-4e31-b8c9-e1ac1f97746e"
          },
          {
            "name": "Confirm Goods Receipt Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Confirm Goods Receipt Date",
            "displayFolder": "Columns\\3. Keys\\Dates",
            "lineageTag": "76a947d9-cf88-49b9-945e-9034a3c2ce17"
          },
          {
            "name": "Customer Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Customer Key",
            "displayFolder": "Columns\\3. Keys",
            "lineageTag": "9496ba22-b180-436d-bcdc-9a1a74722321"
          },
          {
            "name": "Local Currency",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Local Currency",
            "displayFolder": "Columns\\3. Keys",
            "lineageTag": "2022bec1-9cd4-4ac9-993e-9cc85a29646c"
          },
          {
            "name": "Net Order Quantity",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Net Order Quantity",
            "displayFolder": "Columns\\1. Facts",
            "lineageTag": "38503552-7ce2-412c-bb5e-b56bda227eb0"
          },
          {
            "name": "Net Order Value",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Net Order Value",
            "displayFolder": "Columns\\1. Facts",
            "lineageTag": "ce7d5f32-b1d9-4c34-b778-963c65d7931d"
          },
          {
            "name": "Order Date",
            "dataType": "dateTime",
            "description": "There is a bug with the \"Order Date\" field where it is blank. This will take me a bit of time to resolve. - Kurt",
            "isHidden": true,
            "sourceColumn": "Order Date",
            "displayFolder": "Columns\\3. Keys\\Dates",
            "lineageTag": "cca4d6f0-d0b7-47ed-a7c9-8f5aa2a98962"
          },
          {
            "name": "Product Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Product Key",
            "displayFolder": "Columns\\3. Keys",
            "lineageTag": "35a4cdf8-ef86-4d1f-b389-9f9cf1567188"
          },
          {
            "name": "Request Goods Receipt Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Request Goods Receipt Date",
            "displayFolder": "Columns\\3. Keys\\Dates",
            "lineageTag": "1d86455e-0786-4044-a863-46c0f76d2528"
          },
          {
            "name": "Sales Order Document Line Item Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Sales Order Document Line Item Number",
            "displayFolder": "Columns\\2. Document Fields",
            "lineageTag": "3160dd83-6600-4ee8-9352-1f63bf72df1e"
          },
          {
            "name": "Sales Order Document Line Item Status",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sales Order Document Line Item Status",
            "displayFolder": "Columns\\3. Keys",
            "lineageTag": "cd22a20a-de0e-411c-8c1a-bf9806d7dcfe"
          },
          {
            "name": "Sales Order Document Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Sales Order Document Number",
            "displayFolder": "Columns\\2. Document Fields",
            "lineageTag": "163858ac-fb24-4133-adf0-b14dab3c3f36"
          },
          {
            "name": "Sales Order Document Type Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sales Order Document Type Code",
            "displayFolder": "Columns\\3. Keys",
            "lineageTag": "9f790c89-4a50-4f00-9729-4e8219f5ebb4"
          },
          {
            "name": "Ship Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Ship Date",
            "displayFolder": "Columns\\3. Keys\\Dates",
            "lineageTag": "9792bfa7-8c8a-434d-8cad-919bc7f9ecb8"
          }
        ],
        "partitions": [
          {
            "name": "Orders",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SpacePartsDW\",",
                "    Data = Source{[Schema=\"Factview\",Item=\"Orders\"]}[Data],",
                "    #\"Select Columns\" = Table.RemoveColumns ( Data, \"DWCreatedDate\" ),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Select Columns\", \"RandomDays\", each Number.RandomBetween(7, 90), Int64.Type),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"RandomDays\", Int64.Type}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type\", \"Fixed Order Date\", each if [Order Date] = null then Date.AddDays([Request Goods Receipt Date], -[RandomDays]) else [Order Date]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"Fixed Order Date\", type date}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"Order Date\", \"RandomDays\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"Fixed Order Date\", \"Order Date\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Net Orders (Quantity)",
            "description": "Net orders exclude cancellation document types",
            "expression": [
              "",
              "CALCULATE (",
              "    [Total Net Order Quantity],",
              "    'Order Document Type'[Group]",
              "        <> \"Cancellation\"",
              ") "
            ],
            "formatString": "#,##0",
            "displayFolder": "2. Quantity",
            "lineageTag": "735e22bf-4e02-4887-a597-e1dfcdd34aad"
          },
          {
            "name": "Net Orders 1YP",
            "description": "Net orders exclude cancellation document types",
            "expression": [
              "",
              "CALCULATE ( [Net Orders], DATEADD('Date'[Date], -1, YEAR ))"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\ii. 1YP",
            "lineageTag": "ff93215e-8b82-41cd-bfd8-a31541d6dc84"
          },
          {
            "name": "Net Orders 2YP",
            "description": "Net orders exclude cancellation document types",
            "expression": [
              "",
              "CALCULATE ( [Net Orders], DATEADD('Date'[Date], -2, YEAR ))"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\iii. 2YP",
            "lineageTag": "4ace6187-dbc5-4132-a957-a2c2d78d7c0e"
          },
          {
            "name": "Net Orders",
            "description": "Net orders exclude cancellation document types",
            "expression": [
              "",
              "CALCULATE (",
              "    [Total Net Order Value],",
              "    'Order Document Type'[Group]",
              "        <> \"Cancellation\"",
              ") "
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\i. Total",
            "lineageTag": "4b34a3e0-ef13-4b57-8312-568cc0f1083c"
          },
          {
            "name": "Order Lines",
            "expression": [
              "",
              "COUNTROWS ( 'Orders' )"
            ],
            "formatString": "#,##0",
            "displayFolder": "3. Lines",
            "lineageTag": "5324832f-97a5-437f-9604-d6dca47246de"
          },
          {
            "name": "Total Net Order Quantity",
            "expression": [
              "",
              "SUM ( 'Orders'[Net Order Quantity] )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "2. Quantity",
            "lineageTag": "880c9c1a-af07-4b22-b4e8-28a116f6a170"
          },
          {
            "name": "Total Net Order Value",
            "description": "The net order value is the sum of all order intake including cancellations (also known as Gross Orders)",
            "expression": [
              "",
              "VAR _RATE = MAX ('Exchange Rate'[Rate])",
              "RETURN",
              "",
              "    -- Convert to common currency (WAT)",
              "    SUMX (",
              "        'Orders',",
              "        'Orders'[Net Order Value]",
              "            / RELATED ('Budget Rate'[Rate])",
              "    )",
              "",
              "        -- Convert to selected currency",
              "        * _RATE "
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\i. Total",
            "lineageTag": "7bb01c04-5462-4841-93f9-e0d850e8c1cf"
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Fact Tables"
          }
        ]
      },
      {
        "name": "Products",
        "lineageTag": "4963b255-25ef-4ad6-8fc0-3991443146a0",
        "columns": [
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "Color",
            "displayFolder": "2. Product Attributes",
            "lineageTag": "d09831f4-99c0-40cd-b760-3fde292b3c21"
          },
          {
            "name": "Material",
            "dataType": "string",
            "sourceColumn": "Material",
            "displayFolder": "1. Product Hierarchy",
            "lineageTag": "a78bca4e-9fc2-42b7-8e38-44a2800b9ad1"
          },
          {
            "name": "Maximum Temperature (K)",
            "dataType": "int64",
            "sourceColumn": "Maximum Temperature (K)",
            "displayFolder": "4. Product Facts",
            "lineageTag": "2005d462-c934-4b0d-9746-b46329fb408d"
          },
          {
            "name": "MK",
            "dataType": "string",
            "sourceColumn": "MK",
            "displayFolder": "2. Product Attributes",
            "lineageTag": "434ef8cd-463c-423c-98d0-133def571872"
          },
          {
            "name": "Nameplate",
            "dataType": "string",
            "sourceColumn": "Nameplate",
            "displayFolder": "2. Product Attributes",
            "lineageTag": "4e1f18fb-66c0-457f-a7df-65694bfe81de"
          },
          {
            "name": "Part Fit Grading",
            "dataType": "string",
            "sourceColumn": "Part Fit Grading",
            "displayFolder": "2. Product Attributes",
            "lineageTag": "5832f019-fb01-4e09-ab32-ca411cb31e53"
          },
          {
            "name": "Product Business Line Leader",
            "dataType": "string",
            "sourceColumn": "Product Business Line Leader",
            "displayFolder": "3. Product Managers",
            "lineageTag": "f7d90ab0-1767-4d3d-884b-33ce7aab8421"
          },
          {
            "name": "Product Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Product Key",
            "displayFolder": "5. Keys",
            "lineageTag": "0af3eedf-9023-45c6-9b52-df7c4c69ee12"
          },
          {
            "name": "Product Name",
            "dataType": "string",
            "sourceColumn": "Product Name",
            "displayFolder": "1. Product Hierarchy",
            "lineageTag": "31fc2387-5a7f-4655-a5ea-0bc51c07852a"
          },
          {
            "name": "Production Series",
            "dataType": "string",
            "sourceColumn": "Production Series",
            "displayFolder": "2. Product Attributes",
            "lineageTag": "2c8917a4-56c0-41b2-aea6-2b4db37b3711"
          },
          {
            "name": "Ship Class for Part",
            "dataType": "string",
            "sourceColumn": "Ship Class for Part",
            "displayFolder": "2. Product Attributes",
            "lineageTag": "8b05870e-ec7e-4bee-b9cc-3998508fd4c9"
          },
          {
            "name": "Sub Brand Name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sub Brand Name",
            "displayFolder": "5. Keys",
            "lineageTag": "46b52e9b-f065-4a4b-a860-cbd239180893"
          },
          {
            "name": "Subtype",
            "dataType": "string",
            "sourceColumn": "Subtype",
            "displayFolder": "1. Product Hierarchy",
            "lineageTag": "15258ae0-314c-4258-b6a9-c5f4b1f7c0df"
          },
          {
            "name": "Tolerance (g)",
            "dataType": "int64",
            "sourceColumn": "Tolerance (g)",
            "displayFolder": "4. Product Facts",
            "lineageTag": "5b9d9f23-63fd-4aca-99c3-8c2952190f4c"
          },
          {
            "name": "Type",
            "dataType": "string",
            "sourceColumn": "Type",
            "displayFolder": "1. Product Hierarchy",
            "lineageTag": "85080b98-1526-4199-8045-b27395dcead7"
          },
          {
            "name": "Velocity Tolerance (Meters / Second)",
            "dataType": "int64",
            "sourceColumn": "Velocity Tolerance (Meters / Second)",
            "displayFolder": "4. Product Facts",
            "lineageTag": "762198d6-0454-4be8-bd34-93a179964871"
          },
          {
            "name": "Weight (Tonnes)",
            "dataType": "decimal",
            "sourceColumn": "Weight (Tonnes)",
            "displayFolder": "4. Product Facts",
            "lineageTag": "cc3bfcfb-ca3a-48ef-a567-b767efcdf6bd"
          }
        ],
        "partitions": [
          {
            "name": "Products",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SpacePartsDW\",",
                "    Data = Source{[Schema=\"Dimview\",Item=\"Products\"]}[Data]",
                "in",
                "    Data"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "# Products",
            "expression": [
              "",
              "COUNTROWS ( ",
              "    VALUES ( 'Products'[Product Name] )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures",
            "lineageTag": "1fb6f2e9-ed3c-4c97-8fdc-95d1d037a0de"
          }
        ],
        "hierarchies": [
          {
            "name": "Product Hierarchy",
            "displayFolder": "1. Product Hierarchy",
            "lineageTag": "be3e77c0-e9ee-4ef7-947d-d4d075eeee9a",
            "levels": [
              {
                "name": "Type",
                "ordinal": 0,
                "column": "Type",
                "lineageTag": "5dc23be4-9e7d-4d9c-9125-29fff24963af"
              },
              {
                "name": "Subtype",
                "ordinal": 1,
                "column": "Subtype",
                "lineageTag": "aad230ae-d02b-40ca-909f-912eb59dbd84"
              },
              {
                "name": "Product Name",
                "ordinal": 2,
                "column": "Product Name",
                "lineageTag": "2faa8a87-f034-4a37-ae57-78226ae641ee"
              },
              {
                "name": "Material",
                "ordinal": 3,
                "column": "Material",
                "lineageTag": "3f546d11-2759-4b51-bd76-87db29036a7b"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Dimension Tables"
          }
        ]
      },
      {
        "name": "Regions",
        "lineageTag": "bca583de-764e-4d89-9f57-4f9b7afa671f",
        "columns": [
          {
            "name": "All",
            "dataType": "string",
            "sourceColumn": "All",
            "displayFolder": "1. Region Hierarchy",
            "lineageTag": "01dabba0-927a-447c-933e-dd4282827050"
          },
          {
            "name": "Interplanetary Region",
            "dataType": "string",
            "sourceColumn": "Interplanetary Region",
            "displayFolder": "1. Region Hierarchy",
            "lineageTag": "e5e4b390-0dcc-4018-b87c-b484a852f032"
          },
          {
            "name": "Station Sales Managers",
            "dataType": "string",
            "sourceColumn": "Station Sales Managers",
            "displayFolder": "3. Managers",
            "lineageTag": "d38439ea-70ae-4a7f-82b1-6cdd6536ba53"
          },
          {
            "name": "Station Type",
            "dataType": "string",
            "sourceColumn": "Station Type",
            "displayFolder": "2. Region Attributes",
            "lineageTag": "143c4d29-e3be-4b74-9cc2-f2f5b2e31c5c"
          },
          {
            "name": "Station",
            "dataType": "string",
            "sourceColumn": "Station",
            "displayFolder": "1. Region Hierarchy",
            "lineageTag": "448ce04b-4b37-4836-a906-9cbeed4310be"
          },
          {
            "name": "System Regional Managers",
            "dataType": "string",
            "sourceColumn": "System Regional Managers",
            "displayFolder": "3. Managers",
            "lineageTag": "b59ca628-8da1-4052-aa67-ab015c55aaa1"
          },
          {
            "name": "System Sales Directors",
            "dataType": "string",
            "sourceColumn": "System Sales Directors",
            "displayFolder": "3. Managers",
            "lineageTag": "af710796-8d11-4cc9-964f-6571ccfc7f0a"
          },
          {
            "name": "System",
            "dataType": "string",
            "sourceColumn": "System",
            "displayFolder": "1. Region Hierarchy",
            "lineageTag": "33bdc3d4-f515-4abe-9c2b-b07cbf859c2a"
          },
          {
            "name": "Tax Rate",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "Tax Rate",
            "formatString": "#,##0.000",
            "displayFolder": "2. Region Attributes",
            "lineageTag": "39630edd-0932-46c0-9e86-5db2c308b51a"
          },
          {
            "name": "Territory Directors",
            "dataType": "string",
            "sourceColumn": "Territory Directors",
            "displayFolder": "3. Managers",
            "lineageTag": "a55a008d-d15b-4c72-ac32-796786fb4cce"
          },
          {
            "name": "Territory",
            "dataType": "string",
            "sourceColumn": "Territory",
            "displayFolder": "1. Region Hierarchy",
            "lineageTag": "85ec7ff6-21a1-4ccc-bdb0-391f173c7cbb"
          }
        ],
        "partitions": [
          {
            "name": "Regions",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SpacePartsDW\",",
                "    Data = Source{[Schema=\"Dimview\",Item=\"Regions\"]}[Data]",
                "in",
                "    Data"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Regional Hierarchy",
            "displayFolder": "1. Region Hierarchy",
            "lineageTag": "8ce16331-fb01-4dfb-bd38-da99652a4893",
            "levels": [
              {
                "name": "Territory",
                "ordinal": 3,
                "column": "Territory",
                "lineageTag": "006fd1c2-f102-4ed6-b80b-677e2e392747"
              },
              {
                "name": "System",
                "ordinal": 1,
                "column": "System",
                "lineageTag": "eb24e180-a00e-4f4f-9b9f-03f0c2c33521"
              },
              {
                "name": "Station",
                "ordinal": 4,
                "column": "Station",
                "lineageTag": "d6c1f01c-580a-45be-ba9f-a0ce66a12255"
              },
              {
                "name": "Interplanetary Region",
                "ordinal": 2,
                "column": "Interplanetary Region",
                "lineageTag": "df0d47d9-4330-4447-8fc4-7a3dead1f50d"
              },
              {
                "name": "All",
                "ordinal": 0,
                "column": "All",
                "lineageTag": "d0892c44-a314-4400-a33c-1c9e05de3679"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Dimension Tables"
          }
        ]
      },
      {
        "name": "Z01CG1 - Quantity",
        "isHidden": true,
        "lineageTag": "b6f842c2-82d7-4bb1-9831-491a409aec9b",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "Orders",
              "expression": [
                "",
                "[Net Orders (Quantity)]"
              ],
              "ordinal": 1
            },
            {
              "name": "Invoices",
              "expression": [
                "",
                "[Total Net Invoice Quantity]"
              ],
              "ordinal": 2
            },
            {
              "name": "Invoice Cost",
              "description": "The Net Invoice Cost is ",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 3
            },
            {
              "name": "Delivery Cost",
              "description": "The cost of the delivery only",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 4
            },
            {
              "name": "Delivery Surcharge",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 5
            },
            {
              "name": "Taxes",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 6
            },
            {
              "name": "Overdue Payment Penalties",
              "description": "Overdue Payments result when the customer hasn't paid their invoice within a certain number of days since the product was shipped.",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 7
            },
            {
              "name": "Late Delivery Penalties",
              "description": "Late Delivery penalties occur when we fail to meet the SLA for deliveries. If the products take longer than a certain number of days to deliver after the requested delivery date, a Late Delivery Penalty is levied.",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 8
            },
            {
              "name": "Gross Sales",
              "expression": [
                "",
                "[Total Net Invoice Quantity]"
              ],
              "ordinal": 0
            }
          ]
        },
        "columns": [
          {
            "name": "Measure",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal"
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Calculation Groups"
          }
        ]
      },
      {
        "name": "Z01CG2 - Value (Budget Rate)",
        "isHidden": true,
        "lineageTag": "af94bf00-20d7-4871-a2d6-dbcc1e73ad88",
        "calculationGroup": {
          "precedence": 1,
          "calculationItems": [
            {
              "name": "Invoices",
              "expression": [
                "",
                "[Total Net Invoice Value]"
              ],
              "ordinal": 2
            },
            {
              "name": "Orders",
              "expression": [
                "",
                "[Net Orders]"
              ],
              "ordinal": 1
            },
            {
              "name": "Invoice Cost",
              "description": "The Net Invoice Cost is ",
              "expression": [
                "",
                "[Total Net Invoice COGS]"
              ],
              "ordinal": 3
            },
            {
              "name": "Delivery Cost",
              "description": "The cost of the delivery only",
              "expression": [
                "",
                "[Total Delivery Cost]"
              ],
              "ordinal": 4
            },
            {
              "name": "Delivery Surcharge",
              "expression": [
                "",
                "[Total Freight Surcharge]"
              ],
              "ordinal": 5
            },
            {
              "name": "Taxes",
              "expression": [
                "",
                "[Total Taxes & Commercial Fees]"
              ],
              "ordinal": 6
            },
            {
              "name": "Overdue Payment Penalties",
              "description": "Overdue Payments result when the customer hasn't paid their invoice within a certain number of days since the product was shipped.",
              "expression": [
                "",
                "[Total Overdue Payment Penalties]"
              ],
              "ordinal": 7
            },
            {
              "name": "Late Delivery Penalties",
              "description": "Late Delivery penalties occur when we fail to meet the SLA for deliveries. If the products take longer than a certain number of days to deliver after the requested delivery date, a Late Delivery Penalty is levied.",
              "expression": [
                "",
                "[Total Late Delivery Penalties]"
              ],
              "ordinal": 8
            },
            {
              "name": "Gross Sales",
              "expression": [
                "",
                "[Gross Sales]"
              ],
              "ordinal": 0
            }
          ]
        },
        "columns": [
          {
            "name": "Measure",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal"
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Calculation Groups"
          }
        ]
      },
      {
        "name": "Z01CG4 - Lines",
        "isHidden": true,
        "lineageTag": "d0e1c818-c035-4cd9-a3ac-7efb39b1e1a7",
        "calculationGroup": {
          "precedence": 3,
          "calculationItems": [
            {
              "name": "Invoices",
              "expression": [
                "",
                "[Lines]"
              ],
              "ordinal": 3
            },
            {
              "name": "Orders",
              "expression": [
                "",
                "[Net Orders]"
              ],
              "ordinal": 2
            },
            {
              "name": "Invoice Cost",
              "description": "The Net Invoice Cost is ",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 4
            },
            {
              "name": "Delivery Cost",
              "description": "The cost of the delivery only",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 5
            },
            {
              "name": "Delivery Surcharge",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 6
            },
            {
              "name": "Taxes",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 7
            },
            {
              "name": "Overdue Payment Penalties",
              "description": "Overdue Payments result when the customer hasn't paid their invoice within a certain number of days since the product was shipped.",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 8
            },
            {
              "name": "Late Delivery Penalties",
              "description": "Late Delivery penalties occur when we fail to meet the SLA for deliveries. If the products take longer than a certain number of days to deliver after the requested delivery date, a Late Delivery Penalty is levied.",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 9
            },
            {
              "name": "Gross Sales",
              "expression": [
                "",
                "[Invoice Lines]"
              ],
              "ordinal": 0
            },
            {
              "name": "Net Sales",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 1
            }
          ]
        },
        "columns": [
          {
            "name": "Measure",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal"
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Calculation Groups"
          }
        ]
      },
      {
        "name": "Z02CG1 - Unit",
        "isHidden": true,
        "lineageTag": "516121f5-e575-4aef-9915-f766b1aa72e0",
        "calculationGroup": {
          "precedence": 2,
          "calculationItems": [
            {
              "name": "Value (Budget Rate)",
              "expression": [
                "",
                "[Value]"
              ],
              "ordinal": 0
            },
            {
              "name": "Quantity",
              "expression": [
                "",
                "[Quantity]"
              ],
              "ordinal": 2
            },
            {
              "name": "Lines",
              "expression": [
                "",
                "[Lines]"
              ],
              "ordinal": 3
            }
          ]
        },
        "columns": [
          {
            "name": "Unit",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal"
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Calculation Groups"
          }
        ]
      },
      {
        "name": "Z03CG1 - Sales Target",
        "isHidden": true,
        "lineageTag": "04c41956-f84c-47b8-a9d6-c2264d42e1e9",
        "calculationGroup": {
          "precedence": 6,
          "calculationItems": [
            {
              "name": "Budget",
              "expression": [
                "",
                "[Total Budget]"
              ],
              "ordinal": 0
            },
            {
              "name": "1 Year Prior",
              "expression": [
                "",
                "[Gross Sales 1YP (Selected Unit)]"
              ],
              "ordinal": 2
            },
            {
              "name": "Forecast",
              "expression": [
                "",
                "[Forecast]"
              ],
              "ordinal": 1
            },
            {
              "name": "2 Years Prior",
              "expression": [
                "",
                "[Gross Sales 2YP (Selected Unit)]"
              ],
              "ordinal": 3
            }
          ]
        },
        "columns": [
          {
            "name": "Target",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal"
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Calculation Groups"
          }
        ]
      },
      {
        "name": "Z03CG2 - Orders Target",
        "isHidden": true,
        "lineageTag": "03aebfe4-55ef-4d5c-9ffb-173716934b26",
        "calculationGroup": {
          "precedence": 7,
          "calculationItems": [
            {
              "name": "1 Year Prior",
              "expression": [
                "",
                "[Net Orders 1YP]"
              ]
            },
            {
              "name": "2 Years Prior",
              "expression": [
                "",
                "[Net Orders 2YP]"
              ]
            },
            {
              "name": "Budget",
              "expression": [
                "",
                "BLANK()"
              ]
            },
            {
              "name": "Forecast",
              "expression": [
                "",
                "BLANK()"
              ]
            }
          ]
        },
        "columns": [
          {
            "name": "Target",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal"
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Calculation Groups"
          }
        ]
      },
      {
        "name": "Z04CG1 - Time Intelligence",
        "isHidden": true,
        "lineageTag": "06d80604-395e-436b-8758-bf365cf9f944",
        "calculationGroup": {
          "precedence": 4,
          "calculationItems": [
            {
              "name": "Daily",
              "expression": [
                "",
                "SELECTEDMEASURE()"
              ],
              "ordinal": 0
            },
            {
              "name": "MTD",
              "expression": [
                "",
                "CALCULATE (",
                "    SELECTEDMEASURE (), ",
                "    CALCULATETABLE (",
                "        DATESMTD ('Date'[Date]),",
                "        'Date'[IsDateInScope]",
                "    )",
                ")"
              ],
              "ordinal": 1
            },
            {
              "name": "QTD",
              "expression": [
                "",
                "CALCULATE (",
                "    SELECTEDMEASURE (), ",
                "    CALCULATETABLE (",
                "        DATESQTD ('Date'[Date]),",
                "        'Date'[IsDateInScope]",
                "    )",
                ")"
              ],
              "ordinal": 2
            },
            {
              "name": "YTD",
              "expression": [
                "",
                "VAR _YTD =",
                "    CALCULATE (",
                "        SELECTEDMEASURE (),",
                "        CALCULATETABLE (",
                "            DATESYTD ('Date'[Date]),",
                "            'Date'[IsDateInScope]",
                "        )",
                "    )",
                "VAR _FULL_YTD =",
                "    CALCULATE (SELECTEDMEASURE (), DATESYTD ('Date'[Date]))",
                "RETURN",
                "    IF (",
                "        SEARCH (\"Actuals\", SELECTEDMEASURENAME (), , 999) <> 999,",
                "        _YTD,",
                "        _FULL_YTD",
                "    )"
              ],
              "ordinal": 3
            }
          ]
        },
        "columns": [
          {
            "name": "Aggregation",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal"
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Calculation Groups"
          }
        ]
      },
      {
        "name": "__Demo Measures",
        "description": "5 measures usable without any selection; quick-start",
        "lineageTag": "5bfcf671-969d-4907-942e-4ed897cbc246",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "__Measures",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[__Measures]",
            "lineageTag": "7b86f793-f2d4-4efc-be96-092bd800e254"
          }
        ],
        "partitions": [
          {
            "name": "__Demo Measures",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "SELECTCOLUMNS (",
                "    { 1 },",
                "    \"__Measures\", ''[Value]",
                ")"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "# Accounts",
            "expression": [
              "",
              "[# Customers]"
            ],
            "formatString": "#,##0",
            "lineageTag": "be41049e-f8e5-48dd-8d7f-9c14dd274b1a"
          },
          {
            "name": "Billing Document Lines",
            "expression": [
              "",
              "[Invoice Lines]"
            ],
            "formatString": "#,##0",
            "lineageTag": "d69dc0a4-9763-403e-8e38-edb03bb5ec7e"
          },
          {
            "name": "Sales Budget",
            "expression": [
              "",
              "CALCULATE (",
              "    [Budget],",
              "    'Exchange Rate'[Currency] = \"EUR\"",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "e3555966-4f07-443b-a732-838da8defcc2"
          },
          {
            "name": "Sales Forecast",
            "expression": [
              "",
              "CALCULATE (",
              "    [Forecast],",
              "    'Exchange Rate'[Currency] = \"EUR\"",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "d4110b87-0cfc-49d6-8b96-053d05450b96"
          },
          {
            "name": "Sales",
            "expression": [
              "",
              "CALCULATE (",
              "    [Gross Sales],",
              "    'Exchange Rate'[Currency] = \"EUR\"",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "19ea0898-8a9e-43a6-8190-48879e67068e"
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Measure Tables"
          }
        ]
      },
      {
        "name": "__Measures",
        "description": [
          "Everything in this Table Requires Measure Selection",
          "1. Select a Metric ",
          "2. Select a Unit",
          "3. Select a Target",
          "4. Select a Period",
          "5. Select a Currency (from 'Exchange Rate') ",
          "6. Select a Year and/or Month from 'Date'",
          ""
        ],
        "lineageTag": "c1f26e78-ea20-4757-b4d4-89e2237d2584",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "__Measures",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[__Measures]"
          }
        ],
        "partitions": [
          {
            "name": "__Measures",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "SELECTCOLUMNS (",
                "    { 1 },",
                "    \"__Measures\", ''[Value]",
                ")"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Actuals MTD, Data Label",
            "expression": [
              "",
              "-- Max workday in scope",
              "VAR _MAXWD =",
              "    CALCULATE (",
              "        MAX ( 'Date'[Workdays MTD] ),",
              "        'Date'[IsDateInScope],",
              "        ALLEXCEPT ('Date', 'Date'[Calendar Month Year (ie Jan 21)])",
              "    )",
              "",
              "-- Max date in scope",
              "VAR _MAXDT =",
              "    CALCULATE ( MAX ('Date'[Date] ),",
              "        'Date'[IsDateInScope],",
              "        ALLEXCEPT ('Date', 'Date'[Calendar Month Year (ie Jan 21)]) )",
              "RETURN",
              "",
              "    -- If the selected workday = the max workday in scope, return the value",
              "    -- Otherwise return blank (don't show the marker / value)",
              "    IF (",
              "        MAX ('Date'[Workdays MTD]) = _MAXWD",
              "            || MAX ('Date'[Date]) = _MAXDT,",
              "        \"#6e8c95\",",
              "        \"#FFFFFF00\"",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "9. Technical Measures",
            "lineageTag": "a38853fe-b2da-469e-b410-756d6c44e88d"
          },
          {
            "name": "Actuals MTD, Latest Data Point",
            "expression": [
              "",
              "-- Max workday in scope",
              "VAR _MAXWD =",
              "    CALCULATE (",
              "        MAX ( 'Date'[Workdays MTD] ),",
              "        'Date'[IsDateInScope],",
              "        ALLEXCEPT ('Date', 'Date'[Calendar Month Year (ie Jan 21)])",
              "    )",
              "",
              "-- Max date in scope",
              "VAR _MAXDT =",
              "    CALCULATE ( MAX ('Date'[Date] ),",
              "        'Date'[IsDateInScope],",
              "        ALLEXCEPT ('Date', 'Date'[Calendar Month Year (ie Jan 21)]) )",
              "RETURN",
              "",
              "    -- If the selected workday = the max workday in scope, return the value",
              "    -- Otherwise return blank (don't show the marker / value)",
              "    IF (",
              "        MAX ('Date'[Workdays MTD]) = _MAXWD",
              "            || MAX ('Date'[Date]) = _MAXDT,",
              "        [Actuals MTD]",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "9. Technical Measures",
            "lineageTag": "f526af90-be40-4e71-a8af-700e44503379"
          },
          {
            "name": "Actuals MTD",
            "expression": [
              "",
              "CALCULATE (",
              "    [Actuals],",
              "    CALCULATETABLE (",
              "        DATESMTD ('Date'[Date]),",
              "        'Date'[IsDateInScope]",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "2. MTD\\Actuals",
            "lineageTag": "ea39866d-9863-418f-884b-661ffb7be937"
          },
          {
            "name": "Actuals QTD",
            "expression": [
              "",
              "CALCULATE (",
              "    [Actuals],",
              "    CALCULATETABLE (",
              "        DATESQTD ('Date'[Date]),",
              "        'Date'[IsDateInScope]",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "3. QTD\\Actuals",
            "lineageTag": "75670b7b-105c-4bdd-83a1-1ead1595f242"
          },
          {
            "name": "Actuals YTD",
            "expression": [
              "",
              "CALCULATE (",
              "    [Actuals],",
              "    CALCULATETABLE (",
              "        DATESYTD ('Date'[Date]),",
              "        'Date'[IsDateInScope]",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "4. YTD",
            "lineageTag": "cceb1633-c625-4f81-92e9-220b5bcdf28f"
          },
          {
            "name": "Actuals",
            "expression": [
              "",
              "CALCULATE (",
              "    [Blank],",
              "    TREATAS (",
              "        DISTINCT ('2) Selected Unit'[Select a Unit]),",
              "        'Z02CG1 - Unit'[Unit]",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Total\\Actuals",
            "lineageTag": "0a6cef3d-e27e-4055-a718-50e2e16947d2"
          },
          {
            "name": "Blank",
            "expression": [
              "",
              "BLANK ()"
            ],
            "isHidden": true,
            "displayFolder": "9. Technical Measures",
            "lineageTag": "7bc7070b-80ae-431e-8600-63befaa1d5bf"
          },
          {
            "name": "Gross Sales 1YP (Selected Unit)",
            "expression": [
              "",
              "CALCULATE ( [Gross Sales (Selected Unit)], DATEADD('Date'[Date], -1, YEAR ))"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Total\\Sales Target",
            "lineageTag": "77b9b822-0dde-4ece-8dd7-3dd7a1a9bb14"
          },
          {
            "name": "Gross Sales 2YP (Selected Unit)",
            "expression": [
              "",
              "CALCULATE ( [Gross Sales (Selected Unit)], DATEADD('Date'[Date], -2, YEAR ))"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Total\\Sales Target",
            "lineageTag": "7a676e6e-7385-4ce0-acb9-84a987fededa"
          },
          {
            "name": "Lines",
            "expression": [
              "",
              "CALCULATE (",
              "    [Blank],",
              "    TREATAS (",
              "        DISTINCT ('1) Selected Metric'[Select a Measure]),",
              "        'Z01CG4 - Lines'[Measure]",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Total\\Actuals",
            "lineageTag": "70efca37-c432-410e-a447-3025e4237852"
          },
          {
            "name": "Orders Target MTD",
            "expression": [
              "",
              "-- Calculates the target for the current month/year selection",
              "VAR _CurrentMonth =",
              "    CALCULATE (",
              "        [Orders Target],",
              "        ALL ( 'Date' ),",
              "        VALUES (",
              "            'Date'[Calendar Month Year (ie Jan 21)]",
              "        )",
              "    )",
              "",
              "-- Computes rate at which Budget increases through the month",
              "VAR _CurrentMonthWDMTD =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] ),",
              "            'Date'[IsDateInScope] = TRUE",
              "        ),",
              "        0.93",
              "    )",
              "VAR _CurrentMonthWDTotal =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] )",
              "        ),",
              "        0.93",
              "    )",
              "VAR _Period =",
              "    SELECTEDVALUE (",
              "        '4) Selected Period'[Period]",
              "    )",
              "    ",
              "VAR __HasOneMonth =",
              "    HASONEVALUE (",
              "        'Date'[Calendar Month Year (ie Jan 21)]",
              "    )",
              "RETURN",
              "    -- return MTD value if a month is selected",
              "    IF.EAGER (",
              "        __HasOneMonth && _Period = \"Full Period\",",
              "        _CurrentMonthWDTotal",
              "            * _CurrentMonth,",
              "        IF (",
              "            __HasOneMonth,",
              "            _CurrentMonthWDMTD",
              "                * _CurrentMonth",
              "        )",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "2. MTD\\Orders Target",
            "lineageTag": "1d671a50-fac4-4d2b-a41d-3328c522dafa"
          },
          {
            "name": "Orders Target QTD",
            "expression": [
              "",
              "VAR _DATES_QTD =",
              "    CALCULATETABLE (",
              "        DATESQTD ('Date'[Date]),",
              "        'Date'[IsThisMonth] = FALSE",
              "    )",
              "VAR _CURRENT_MONTH_Forecast = [Orders Target MTD]",
              "VAR _QTD_Forecast_BEFORE_THIS_MONTH = CALCULATE ([Orders Target], _DATES_QTD)",
              "VAR _RESULT = _CURRENT_MONTH_Forecast + _QTD_Forecast_BEFORE_THIS_MONTH",
              "RETURN",
              "    _RESULT"
            ],
            "formatString": "#,##0",
            "displayFolder": "3. QTD\\Orders Target",
            "lineageTag": "8592bd67-7145-4ca4-ba42-fa3e0defba2e"
          },
          {
            "name": "Orders Target vs. Net Orders (%)",
            "description": "Net orders exclude cancellation document types",
            "expression": [
              "",
              "VAR _TARGET = [Orders Target]",
              "VAR _DELTA  = [Net Orders] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "1. Total\\Orders Target",
            "lineageTag": "e6cda3c8-6f0c-4d5a-8685-d41623fb81d9"
          },
          {
            "name": "Orders Target vs. Net Orders (Δ)",
            "description": "Net orders exclude cancellation document types",
            "expression": [
              "",
              "[Net Orders] - [Orders Target]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "1. Total\\Orders Target",
            "lineageTag": "baee51d7-d773-4a52-9486-6aed36e264c0"
          },
          {
            "name": "Orders Target YTD",
            "expression": [
              "",
              "VAR _CURRENT_MONTH_TARGET = [Orders Target MTD]",
              "VAR _YTD_TARGET_BEFORE_THIS_MONTH =",
              "    CALCULATE (",
              "        [Orders Target],",
              "        CALCULATETABLE (",
              "            DATESYTD ('Date'[Date]),",
              "            'Date'[IsThisMonth] = FALSE,",
              "            'Date'[IsDateInScope] = TRUE",
              "        )",
              "    )",
              "VAR _RESULT = _CURRENT_MONTH_TARGET + _YTD_TARGET_BEFORE_THIS_MONTH",
              "RETURN",
              "    _RESULT"
            ],
            "formatString": "#,##0",
            "displayFolder": "4. YTD",
            "lineageTag": "056c010c-5b3c-4faa-a65e-daeb3231600d"
          },
          {
            "name": "Orders Target",
            "expression": [
              "",
              "CALCULATE (",
              "    [Blank],",
              "    TREATAS (",
              "        DISTINCT ( '3) Selected Target'[Select a Target] ), 'Z03CG2 - Orders Target'[Target] )",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Total\\Orders Target",
            "lineageTag": "4eed64a0-d832-4f27-ae28-91d1dc31cb89"
          },
          {
            "name": "Quantity",
            "expression": [
              "",
              "CALCULATE (",
              "    [Blank],",
              "    TREATAS (",
              "        DISTINCT ('1) Selected Metric'[Select a Measure]),",
              "        'Z01CG1 - Quantity'[Measure])",
              ")"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Total\\Actuals",
            "lineageTag": "c68488fd-5631-4b9f-a9c3-7f17d7f6a2ef"
          },
          {
            "name": "Sales Target MTD vs. Actuals (%)",
            "expression": [
              "",
              "VAR _TARGET = [Sales Target MTD]",
              "VAR _ACTUAL = [Actuals MTD]",
              "VAR _DELTA  = _ACTUAL - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "",
              "RETURN",
              "",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "2. MTD\\Sales Target",
            "lineageTag": "2d7fff67-3495-4143-b0e4-2322aca32642"
          },
          {
            "name": "Sales Target MTD vs. Actuals (Δ)",
            "expression": [
              "",
              "[Actuals MTD] - [Sales Target MTD]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "2. MTD\\Sales Target",
            "lineageTag": "30488de0-5eac-468b-a3db-81eea38a2165"
          },
          {
            "name": "Sales Target MTD",
            "expression": [
              "",
              "-- Calculates the target for the current month/year selection",
              "VAR _CurrentMonth =",
              "    CALCULATE (",
              "        [Sales Target],",
              "        ALL ( 'Date' ),",
              "        VALUES (",
              "            'Date'[Calendar Month Year (ie Jan 21)]",
              "        )",
              "    )",
              "",
              "-- Computes rate at which Budget increases through the month",
              "VAR _CurrentMonthWDMTD =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] ),",
              "            'Date'[IsDateInScope] = TRUE",
              "        ),",
              "        1.035",
              "    )",
              "VAR CurrentMonthWDTotal =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] )",
              "        ),",
              "        1.035",
              "    )",
              "VAR _Period =",
              "    SELECTEDVALUE (",
              "        '4) Selected Period'[Period]",
              "    )",
              "VAR _HasOneMonth =",
              "    HASONEVALUE (",
              "        'Date'[Calendar Month Year (ie Jan 21)]",
              "    )",
              "RETURN",
              "    -- return MTD value if a month is selected",
              "    IF.EAGER (",
              "        _HasOneMonth && _Period = \"Full Period\",",
              "        CurrentMonthWDTotal",
              "            * _CurrentMonth,",
              "        IF (",
              "            _HasOneMonth,",
              "            _CurrentMonthWDMTD",
              "                * _CurrentMonth",
              "        )",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "2. MTD\\Sales Target",
            "lineageTag": "528d4072-5ea6-4427-97e0-7e812a0f511a"
          },
          {
            "name": "Sales Target QTD",
            "expression": [
              "",
              "VAR _QTD =",
              "    CALCULATE(",
              "        [Sales Target],",
              "        CALCULATETABLE(",
              "            DATESQTD( 'Date'[Date] ),",
              "            'Date'[IsDateInScope] = TRUE",
              "        ),",
              "        'Date'[IsThisMonth] = FALSE",
              "    )",
              "VAR _MTD =",
              "    CALCULATE( [Sales Target MTD], 'Date'[IsThisMonth] = TRUE )",
              "VAR _PERIOD = SELECTEDVALUE( '4) Selected Period'[Period] )",
              "VAR _QUARTER = MAX( 'Date'[Calendar Year Quarter (ie 202101)] )",
              "VAR _MONTH = MAX( 'Date'[Calendar Year Month (ie 202101)] )",
              "RETURN",
              "    IF(",
              "        _PERIOD = \"Full Period\",",
              "        CALCULATE(",
              "            [Sales Target],",
              "            ALL( 'Date' ),",
              "            'Date'[Calendar Year Quarter (ie 202101)] = _QUARTER,",
              "            'Date'[Calendar Year Month (ie 202101)] <= _MONTH",
              "        ),",
              "        IF(",
              "            ISBLANK( _QTD ),",
              "            _MTD,",
              "            // If date is in the visual context and QTD is blank, show MTD, otherwise add QTD + MTD together",
              "            IF( MAX ( 'Date'[Date] ) >= MAX ('Last Refresh'[Last Refresh]), _QTD + _MTD, _QTD )",
              "        )",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "3. QTD\\Sales Target",
            "lineageTag": "5e01dd13-583d-429c-9ba4-79b2fc89b918"
          },
          {
            "name": "Sales Target vs. Actuals (%)",
            "expression": [
              "",
              "VAR _TARGET = [Sales Target]",
              "VAR _ACTUAL = [Actuals]",
              "VAR _DELTA  = _ACTUAL - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "",
              "RETURN",
              "",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "1. Total\\Sales Target",
            "lineageTag": "876d123c-de76-4a10-84e7-470eed31b8c8"
          },
          {
            "name": "Sales Target vs. Actuals (Δ)",
            "expression": [
              "",
              "[Actuals] - [Sales Target]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "1. Total\\Sales Target",
            "lineageTag": "79869441-9511-4efb-b95a-147eb3d14926"
          },
          {
            "name": "Sales Target YTD vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Sales Target YTD]",
              "VAR _DELTA  = [Actuals YTD] -  _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "4. YTD",
            "lineageTag": "0886ae94-a618-4cb5-a879-159717597f72"
          },
          {
            "name": "Sales Target YTD vs. Gross Sales (Δ)",
            "expression": [
              "",
              "[Actuals YTD] - [Sales Target YTD]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "4. YTD",
            "lineageTag": "60e7cc65-3801-4cf5-b186-7216e43c7086"
          },
          {
            "name": "Sales Target YTD",
            "expression": [
              "",
              "VAR YRTD =",
              "    CALCULATE(",
              "        [Sales Target],",
              "        CALCULATETABLE(",
              "            DATESYTD( 'Date'[Date] ),",
              "            'Date'[IsDateInScope] = TRUE",
              "        ),",
              "        'Date'[IsBeforeThisMonth] = TRUE",
              "    ) // Calculates the target for the current month/year selection",
              "VAR _CurrentMonth_value =",
              "    CALCULATE( [Sales Target], 'Date'[IsThisMonth] = TRUE ) // Calculates the % workdays MTD together with the dynamic parameter to set the exponential rate of increase MTD",
              "VAR _currentMonthWorkDay =",
              "    POWER(",
              "        CALCULATE(",
              "            MAX( 'Date'[Workdays MTD %] ),",
              "            'Date'[IsDateInScope] = TRUE,",
              "            'Date'[IsThisMonth] = TRUE",
              "        ),",
              "        0.93",
              "    ) // If viewing units, hide the FCST (as there is no units FCST as of July 09, 2020)",
              "VAR MOTD =",
              "    IF(",
              "        _CurrentMonth_value > 0,",
              "        _currentMonthWorkDay * _CurrentMonth_value,",
              "        BLANK( )",
              "    )",
              "        + YRTD",
              "VAR _PERIOD = SELECTEDVALUE( '4) Selected Period'[Period] )",
              "VAR _YEAR = MAX( 'Date'[Calendar Year Number (ie 2021)] )",
              "VAR _MONTH = MAX( 'Date'[Calendar Year Month (ie 202101)] )",
              "RETURN",
              "    IF(",
              "        _PERIOD = \"Full Period\",",
              "        CALCULATE(",
              "            [Sales Target],",
              "            ALL( 'Date' ),",
              "            'Date'[Calendar Year Number (ie 2021)] = _YEAR,",
              "            'Date'[Calendar Year Month (ie 202101)] <= _MONTH",
              "        ),",
              "        // If date is in the visual context and YTD is blank, show MTD, otherwise add YTD + MTD together",
              "        MOTD",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "4. YTD",
            "lineageTag": "8baefb39-9d1b-40ad-9ad5-4f9c9c310095"
          },
          {
            "name": "Sales Target",
            "expression": [
              "",
              "CALCULATE (",
              "    [Blank],",
              "    TREATAS (",
              "        DISTINCT (",
              "            '3) Selected Target'[Select a Target]",
              "        ),",
              "        'Z03CG1 - Sales Target'[Target]",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Total\\Sales Target",
            "lineageTag": "14bbba44-f1d9-49ad-ab20-4c7910d9d7da"
          },
          {
            "name": "Value",
            "expression": [
              "",
              "CALCULATE (",
              "    [Blank],",
              "    TREATAS (",
              "        DISTINCT ('1) Selected Metric'[Select a Measure]),",
              "        'Z01CG2 - Value (Budget Rate)'[Measure]",
              "    )",
              ") "
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Total\\Actuals",
            "lineageTag": "c5c7fd2d-5b7d-467c-953c-71338d4296f7"
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Measure Tables"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "Relationship",
        "fromTable": "Budget",
        "fromColumn": "Customer Key",
        "toTable": "Customers",
        "toColumn": "Customer Key"
      },
      {
        "name": "Relationship 1",
        "fromTable": "Budget",
        "fromColumn": "Month",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "Relationship 2",
        "fromTable": "Budget",
        "fromColumn": "Product Key",
        "toTable": "Products",
        "toColumn": "Product Key"
      },
      {
        "name": "Relationship 3",
        "fromTable": "Customers",
        "fromColumn": "Station",
        "toTable": "Regions",
        "toColumn": "Station"
      },
      {
        "name": "Relationship 4",
        "fromTable": "Exchange Rate",
        "fromColumn": "Date",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "Relationship 5",
        "fromTable": "Forecast",
        "fromColumn": "Month",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "Relationship 6",
        "toCardinality": "many",
        "fromTable": "Forecast",
        "fromColumn": "Product Type",
        "toTable": "Products",
        "toColumn": "Type"
      },
      {
        "name": "Relationship 7",
        "toCardinality": "many",
        "fromTable": "Forecast",
        "fromColumn": "Region Territory",
        "toTable": "Regions",
        "toColumn": "Territory"
      },
      {
        "name": "Relationship 8",
        "fromTable": "Invoices",
        "fromColumn": "Billing Date",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "Relationship 9",
        "fromTable": "Invoices",
        "fromColumn": "Billing Document Type Code",
        "toTable": "Invoice Document Type",
        "toColumn": "Code"
      },
      {
        "name": "Relationship 10",
        "fromTable": "Invoices",
        "fromColumn": "Customer Key",
        "toTable": "Customers",
        "toColumn": "Customer Key"
      },
      {
        "name": "Relationship 11",
        "fromTable": "Invoices",
        "fromColumn": "Local Currency",
        "toTable": "Budget Rate",
        "toColumn": "From Currency"
      },
      {
        "name": "Relationship 12",
        "fromTable": "Invoices",
        "fromColumn": "OTD Indicator",
        "toTable": "On-Time Delivery",
        "toColumn": "OTD Indicator"
      },
      {
        "name": "Relationship 13",
        "fromTable": "Invoices",
        "fromColumn": "Product Key",
        "toTable": "Products",
        "toColumn": "Product Key"
      },
      {
        "name": "Relationship 14",
        "fromTable": "Orders",
        "fromColumn": "Customer Key",
        "toTable": "Customers",
        "toColumn": "Customer Key"
      },
      {
        "name": "Relationship 15",
        "fromTable": "Orders",
        "fromColumn": "Local Currency",
        "toTable": "Budget Rate",
        "toColumn": "From Currency"
      },
      {
        "name": "Relationship 16",
        "fromTable": "Orders",
        "fromColumn": "Order Date",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "Relationship 17",
        "fromTable": "Orders",
        "fromColumn": "Product Key",
        "toTable": "Products",
        "toColumn": "Product Key"
      },
      {
        "name": "Relationship 18",
        "fromTable": "Orders",
        "fromColumn": "Request Goods Receipt Date",
        "toTable": "Date",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "Relationship 19",
        "fromTable": "Orders",
        "fromColumn": "Sales Order Document Line Item Status",
        "toTable": "Order Status",
        "toColumn": "Order Status Code"
      },
      {
        "name": "Relationship 20",
        "fromTable": "Orders",
        "fromColumn": "Sales Order Document Type Code",
        "toTable": "Order Document Type",
        "toColumn": "Sales Order Document Type Code"
      },
      {
        "name": "Relationship 21",
        "fromTable": "Products",
        "fromColumn": "Sub Brand Name",
        "toTable": "Brands",
        "toColumn": "Sub Brand"
      }
    ],
    "perspectives": [
      {
        "name": "Measure Selection"
      },
      {
        "name": "No Measure Selection",
        "tables": [
          {
            "name": "Last Refresh",
            "measures": [
              {
                "name": "Last Refresh Date"
              }
            ]
          },
          {
            "name": "On-Time Delivery",
            "measures": [
              {
                "name": "OTD % (Lines)"
              },
              {
                "name": "OTD % (Quantity)"
              },
              {
                "name": "OTD % (Value)"
              },
              {
                "name": "OTD (Lines)"
              },
              {
                "name": "OTD (Quantity)"
              },
              {
                "name": "OTD (Value)"
              }
            ]
          },
          {
            "name": "Order Document Type",
            "columns": [
              {
                "name": "Group"
              },
              {
                "name": "Text"
              }
            ]
          },
          {
            "name": "Order Status",
            "columns": [
              {
                "name": "Group"
              },
              {
                "name": "Text"
              }
            ]
          },
          {
            "name": "Orders",
            "measures": [
              {
                "name": "Net Orders (Quantity)"
              },
              {
                "name": "Net Orders 1YP"
              },
              {
                "name": "Net Orders 2YP"
              },
              {
                "name": "Net Orders"
              },
              {
                "name": "Order Lines"
              },
              {
                "name": "Total Net Order Quantity"
              },
              {
                "name": "Total Net Order Value"
              }
            ]
          }
        ]
      }
    ],
    "expressions": [
      {
        "name": "Database",
        "kind": "m",
        "expression": [
          "",
          "\"SpacePartsCoDW\" meta",
          "[",
          "\tIsParameterQuery = true,",
          "\tIsParameterQueryRequired = true,",
          "\tType = type text",
          "]"
        ],
        "lineageTag": "423d49f9-2077-4e20-b035-c615e286df5e"
      },
      {
        "name": "RangeEnd",
        "kind": "m",
        "expression": [
          "",
          "    #datetime(2023, 31, 01, 0, 0, 0) meta",
          "    [",
          "        IsParameterQuery = true,",
          "        IsParameterQueryRequired = true,",
          "        Type = type datetime",
          "    ]"
        ],
        "lineageTag": "eafae8e4-e0dd-4b47-8125-3149da661455"
      },
      {
        "name": "RangeStart",
        "kind": "m",
        "expression": [
          "",
          "    #datetime(2023, 01, 01, 0, 0, 0) meta",
          "    [",
          "        IsParameterQuery = true,",
          "        IsParameterQueryRequired = true,",
          "        Type = type datetime",
          "    ]"
        ],
        "lineageTag": "f5c9c445-899a-4c4a-be86-ec32fc7dfe18"
      },
      {
        "name": "SqlEndpoint",
        "kind": "m",
        "expression": [
          "",
          "\"te3-training-eu.database.windows.net\" meta",
          "[",
          "\tIsParameterQuery = true,",
          "\tIsParameterQueryRequired = true,",
          "\tType = type text",
          "]"
        ],
        "lineageTag": "c5701a1a-761b-4a4f-abb2-8bb5e7de8d4d"
      }
    ],
    "annotations": [
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":true,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Relationships\",\"Roles\",\"Shared Expressions\",\"Tables\",\"Tables/Calculation Items\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Translations\"],\"IgnoreIncrementalRefreshPartitions\":true}"
      },
      {
        "name": "DataGoblins_SnekHighScore",
        "value": "3"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ]
  }
}